"""
detect_hardware.py -- Run AFTER activating the venv.
Usage:
    cd C:\\Users\\alexa\\algo_trading
    .\\venv\\Scripts\\Activate.ps1
    python detect_hardware.py
"""

import os
import sys
import subprocess
import multiprocessing


def detect_cpu():
    logical = multiprocessing.cpu_count()
    physical = logical

    try:
        result = subprocess.run(
            ['wmic', 'cpu', 'get', 'NumberOfCores', '/value'],
            capture_output=True, text=True, timeout=10
        )
        for line in result.stdout.strip().split('\n'):
            if 'NumberOfCores' in line:
                physical = int(line.split('=')[1].strip())
    except Exception:
        physical = logical // 2 or 1

    cpu_name = "Unknown"
    try:
        result = subprocess.run(
            ['wmic', 'cpu', 'get', 'Name', '/value'],
            capture_output=True, text=True, timeout=10
        )
        for line in result.stdout.strip().split('\n'):
            if 'Name' in line:
                cpu_name = line.split('=', 1)[1].strip()
    except Exception:
        pass

    return {
        'name': cpu_name,
        'physical_cores': physical,
        'logical_cores': logical,
    }


def detect_gpu():
    gpu_info = {
        'available': False,
        'name': None,
        'vram_mb': None,
        'cuda_version': None,
        'driver_version': None,
    }

    try:
        result = subprocess.run(
            ['nvidia-smi', '--query-gpu=name,memory.total,driver_version',
             '--format=csv,noheader,nounits'],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            parts = result.stdout.strip().split(',')
            gpu_info['available'] = True
            gpu_info['name'] = parts[0].strip()
            gpu_info['vram_mb'] = int(float(parts[1].strip()))
            gpu_info['driver_version'] = parts[2].strip()
    except FileNotFoundError:
        print("  [!] nvidia-smi not found")
    except Exception as e:
        print(f"  [!] GPU detection error: {e}")

    try:
        result = subprocess.run(
            ['nvcc', '--version'],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            for line in result.stdout.split('\n'):
                if 'release' in line.lower():
                    gpu_info['cuda_version'] = line.strip()
    except FileNotFoundError:
        gpu_info['cuda_version'] = "nvcc not found"
    except Exception:
        pass

    return gpu_info


def detect_ram():
    try:
        result = subprocess.run(
            ['wmic', 'computersystem', 'get', 'TotalPhysicalMemory', '/value'],
            capture_output=True, text=True, timeout=10
        )
        for line in result.stdout.strip().split('\n'):
            if 'TotalPhysicalMemory' in line:
                ram_bytes = int(line.split('=')[1].strip())
                return round(ram_bytes / (1024**3), 1)
    except Exception:
        pass
    return 0


def test_lightgbm_gpu():
    try:
        import lightgbm as lgb
        import numpy as np

        X = np.random.rand(100, 5)
        y = np.random.randint(0, 2, 100)

        params = {
            'objective': 'binary',
            'device': 'gpu',
            'verbose': -1,
            'num_iterations': 5,
        }
        ds = lgb.Dataset(X, label=y)
        lgb.train(params, ds, num_boost_round=5)
        return True
    except Exception as e:
        print(f"  [!] LightGBM GPU test failed: {e}")
        return False


def generate_config(cpu, gpu, ram, lgbm_gpu):
    n_cores = cpu['logical_cores']
    use_gpu = gpu['available'] and lgbm_gpu
    n_jobs_parallel = max(1, n_cores - 2)
    device_str = 'gpu' if use_gpu else 'cpu'

    config = f'''"""
hardware_config.py -- Auto-generated by detect_hardware.py
Detected hardware configuration for this computer.
Re-run detect_hardware.py if you change hardware.
"""

# === CPU ===
CPU_NAME = "{cpu['name']}"
PHYSICAL_CORES = {cpu['physical_cores']}
LOGICAL_CORES = {cpu['logical_cores']}
N_JOBS_PARALLEL = {n_jobs_parallel}   # For joblib Phase 1 (CPU-only configs)

# === GPU ===
GPU_AVAILABLE = {use_gpu}
GPU_NAME = {repr(gpu['name'])}
GPU_VRAM_MB = {gpu['vram_mb']}

# === RAM ===
TOTAL_RAM_GB = {ram}

# === LightGBM Device ===
LGBM_DEVICE = "{device_str}"

# === Model Definitions (adapted for this hardware) ===
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression


def get_cpu_models():
    """Models for Phase 1 -- CPU parallel workers (n_jobs=1 per model to avoid nested parallelism)."""
    return {{
        'RF': RandomForestClassifier(n_estimators=300, max_depth=4, n_jobs=1, random_state=42),
        'GB': GradientBoostingClassifier(n_estimators=300, max_depth=3, random_state=42),
        'LR': LogisticRegression(max_iter=1000, random_state=42),
    }}


def get_gpu_models():
    """Models for Phase 2 -- GPU sequential (RF gets full CPU, LGBM gets GPU)."""
    import lightgbm as lgb
    models = {{
        'RF': RandomForestClassifier(n_estimators=300, max_depth=4, n_jobs=-1, random_state=42),
        'GB': GradientBoostingClassifier(n_estimators=300, max_depth=3, random_state=42),
        'LR': LogisticRegression(max_iter=1000, random_state=42),
        'LGBM': lgb.LGBMClassifier(
            n_estimators=300, max_depth=4, learning_rate=0.05,
            device="{device_str}",
            verbose=-1, random_state=42,
        ),
    }}
    return models


def get_all_models():
    """All models for signal generation (not in parallel)."""
    import lightgbm as lgb
    return {{
        'RF': RandomForestClassifier(n_estimators=300, max_depth=4, n_jobs=-1, random_state=42),
        'GB': GradientBoostingClassifier(n_estimators=300, max_depth=3, random_state=42),
        'LR': LogisticRegression(max_iter=1000, random_state=42),
        'LGBM': lgb.LGBMClassifier(
            n_estimators=300, max_depth=4, learning_rate=0.05,
            device="{device_str}",
            verbose=-1, random_state=42,
        ),
    }}


# === Diagnostic Split ===
# Phase 1: 35 configs without LGBM -- joblib parallel across {n_jobs_parallel} cores
# Phase 2: 40 configs with LGBM -- sequential on {'GPU' if use_gpu else 'CPU'}
'''
    return config


def main():
    print("=" * 60)
    print("  ALGO TRADING -- HARDWARE DETECTION")
    print("=" * 60)

    print("\n[1/4] Detecting CPU...")
    cpu = detect_cpu()
    print(f"  CPU: {cpu['name']}")
    print(f"  Physical cores: {cpu['physical_cores']}")
    print(f"  Logical cores:  {cpu['logical_cores']}")

    print("\n[2/4] Detecting RAM...")
    ram = detect_ram()
    if ram:
        print(f"  Total RAM: {ram} GB")
    else:
        print("  Could not detect RAM")

    print("\n[3/4] Detecting GPU...")
    gpu = detect_gpu()
    if gpu['available']:
        print(f"  GPU: {gpu['name']}")
        print(f"  VRAM: {gpu['vram_mb']} MB")
        print(f"  Driver: {gpu.get('driver_version', 'N/A')}")
        print(f"  CUDA: {gpu.get('cuda_version', 'N/A')}")
    else:
        print("  No NVIDIA GPU detected")

    print("\n[4/4] Testing LightGBM GPU...")
    lgbm_gpu = False
    if gpu['available']:
        lgbm_gpu = test_lightgbm_gpu()
        if lgbm_gpu:
            print("  LightGBM GPU: WORKING")
        else:
            print("  LightGBM GPU: FAILED -- will use CPU fallback")
    else:
        print("  Skipped (no GPU)")

    # Generate config
    print("\n" + "=" * 60)
    config_code = generate_config(cpu, gpu, ram, lgbm_gpu)

    config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'hardware_config.py')
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(config_code)
    print(f"  Config saved to: {config_path}")

    # Summary
    n_jobs = max(1, cpu['logical_cores'] - 2)
    device = 'GPU' if (gpu['available'] and lgbm_gpu) else 'CPU'
    print(f"\n  SUMMARY")
    print(f"  ----------------------------------------")
    print(f"  CPU cores for parallel: {n_jobs}")
    print(f"  LGBM device: {device.lower()}")
    print(f"  Phase 1 (CPU parallel): 35 configs across {n_jobs} workers")
    print(f"  Phase 2 ({device} sequential): 40 configs")
    print("=" * 60)


if __name__ == '__main__':
    main()
