"""
test_per_regime_max_hold.py — standalone harness for Approach #1 (Kaminski-Lo
momentum-conditional max_hold). Tests per-regime max_hold sweep WITHOUT
modifying any production files.

Reads (as inputs only):
  - data/eth_sl_signals_90d.pkl   (regenerated by extend_caches_90d.py)
  - config/regime_config_ed.json  (current live config: detector, horizons, confs, gates)

Re-implements the regime-switched simulator locally with per-regime max_hold
support. Runs full grid: bull_hold ∈ {6,8,10,14,18} × bear_hold ∈ {6,8,10,14,18}
× shield combos {OFF/OFF, ON/OFF, OFF/ON, ON/ON} × min_sell_pnl ∈ {0.5}.

Writes (outputs only):
  - output/per_regime_max_hold_<timestamp>.csv  (full sweep results)

Does NOT touch:
  - models/crypto_ed_production.csv
  - config/regime_config_ed.json
  - any _noprod or live-trader file

Usage:
  python tools/test_per_regime_max_hold.py
  python tools/test_per_regime_max_hold.py --days 60 --min-sell-pnl 0.5
  python tools/test_per_regime_max_hold.py --days 30   # shorter window
"""
from __future__ import annotations

import argparse
import json
import os
import pickle
import sys
from datetime import datetime
from itertools import product

import numpy as np
import pandas as pd

ENGINE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ENGINE, 'data', 'eth_sl_signals_90d.pkl')
REGIME_CFG = os.path.join(ENGINE, 'config', 'regime_config_ed.json')
FEE = 0.0005

BULL_HOLDS_DEFAULT = [6, 8, 10, 14, 18]
BEAR_HOLDS_DEFAULT = [6, 8, 10, 14, 18]


def load_sigs():
    with open(CACHE, 'rb') as f:
        sigs = pickle.load(f)
    for s in sigs:
        s['datetime'] = pd.Timestamp(s['datetime'])
    sigs.sort(key=lambda s: s['datetime'])
    return sigs


def window_slice(sigs, days):
    end = sigs[-1]['datetime']
    lo = end - pd.Timedelta(days=days)
    return [s for s in sigs if s['datetime'] >= lo]


def get_rally_tuple(asset_cfg, regime):
    """Per-regime rally cooldown with asset-level fallback."""
    block = asset_cfg.get(regime, {})
    rc = block.get('rally_cooldown') if isinstance(block, dict) else None
    rc = rc or asset_cfg.get('rally_cooldown')
    if not rc or not rc.get('enabled'):
        return None
    try:
        return (int(rc['h_short']), int(rc['h_long']),
                float(rc['t_short_pct']), float(rc['t_long_pct']),
                int(rc['cd_hours']))
    except (KeyError, TypeError, ValueError):
        return None


def sim_regime_switched(sigs, asset_cfg,
                        bull_min_pnl, bear_min_pnl,
                        bull_max_hold, bear_max_hold,
                        bull_shield, bear_shield,
                        bull_rally_cfg, bear_rally_cfg, fee=FEE):
    """Single-pool regime-switched simulator with PER-REGIME max_hold and
    PER-REGIME min_sell_pnl. Mirrors live trader's process_asset SELL path
    but uses regime-conditional values.

    Returns: (return_pct, n_trades, win_rate, blocked_count, max_hold_fires,
              max_hold_pnl_sum, trades_log)
    """
    bull_conf = float(asset_cfg.get('bull', {}).get('min_confidence', 80))
    bear_conf = float(asset_cfg.get('bear', {}).get('min_confidence', 65))

    # Build regime tagging from sigs (each cached signal already has 'regime'
    # assigned by extend_caches_90d.py).
    closes = np.array([float(s['close']) for s in sigs])

    def _rr(h):
        out = np.full(len(closes), np.nan)
        if h and h < len(closes):
            out[h:] = (closes[h:] / closes[:-h] - 1.0) * 100.0
        return out

    bh_s = bh_l = 0
    bt_s = bt_l = 0.0
    bcd_h = 0
    bull_rs = bull_rl = None
    if bull_rally_cfg is not None:
        bh_s, bh_l, bt_s, bt_l, bcd_h = bull_rally_cfg
        bull_rs = _rr(bh_s)
        bull_rl = _rr(bh_l)
    rh_s = rh_l = 0
    rt_s = rt_l = 0.0
    rcd_h = 0
    bear_rs = bear_rl = None
    if bear_rally_cfg is not None:
        rh_s, rh_l, rt_s, rt_l, rcd_h = bear_rally_cfg
        bear_rs = _rr(rh_s)
        bear_rl = _rr(rh_l)

    cash = 1000.0
    held = 0.0
    in_pos = False
    entry_px = 0.0
    entry_dt = None
    entry_regime = None
    hold_since_entry = 0
    bull_cd = bear_cd = 0
    trade_log = []
    blocked = 0
    max_hold_fires = 0
    max_hold_pnl_sum = 0.0

    for i, s in enumerate(sigs):
        price = float(s['close'])
        regime = s.get('regime', 'bull')
        sig = s['signal']
        sconf = float(s.get('confidence', 0))
        conf_thr = bull_conf if regime == 'bull' else bear_conf
        shield_on = bull_shield if regime == 'bull' else bear_shield
        min_pnl = bull_min_pnl if regime == 'bull' else bear_min_pnl
        active_max_hold = bull_max_hold if regime == 'bull' else bear_max_hold

        if in_pos:
            hold_since_entry += 1

        # Gate triggers (each regime arms its own cooldown)
        if bcd_h > 0 and bull_rs is not None:
            rs = bull_rs[i] if not np.isnan(bull_rs[i]) else 0
            rl = bull_rl[i] if not np.isnan(bull_rl[i]) else 0
            if rs >= bt_s or rl >= bt_l:
                bull_cd = max(bull_cd, bcd_h)
        if rcd_h > 0 and bear_rs is not None:
            rs = bear_rs[i] if not np.isnan(bear_rs[i]) else 0
            rl = bear_rl[i] if not np.isnan(bear_rl[i]) else 0
            if rs >= rt_s or rl >= rt_l:
                bear_cd = max(bear_cd, rcd_h)
        active_cd = bull_cd if regime == 'bull' else bear_cd

        if sig == 'BUY' and sconf >= conf_thr and not in_pos and active_cd <= 0:
            held = cash * (1 - fee) / price
            cash = 0
            in_pos = True
            entry_px = price
            entry_dt = s['datetime']
            entry_regime = regime
            hold_since_entry = 0
        elif sig == 'SELL' and in_pos:
            cur_pnl = (price / entry_px - 1) * 100
            override_expired = hold_since_entry >= active_max_hold
            shield_blocks = shield_on and min_pnl > 0 and cur_pnl < min_pnl
            if not shield_blocks or override_expired:
                exit_reason = 'MODEL'
                if shield_on and override_expired and cur_pnl < min_pnl:
                    exit_reason = 'MAX_HOLD'
                    max_hold_fires += 1
                    max_hold_pnl_sum += cur_pnl
                cash = held * price * (1 - fee)
                trade_log.append({
                    'entry_dt': entry_dt, 'exit_dt': s['datetime'],
                    'pnl_pct': cur_pnl, 'hold_h': hold_since_entry,
                    'regime': entry_regime, 'exit_reason': exit_reason,
                })
                held = 0
                in_pos = False
                hold_since_entry = 0
            else:
                blocked += 1

        if bull_cd > 0:
            bull_cd -= 1
        if bear_cd > 0:
            bear_cd -= 1

    # Close open position at end
    if in_pos:
        final_px = float(sigs[-1]['close'])
        cur_pnl = (final_px / entry_px - 1) * 100
        cash = held * final_px * (1 - fee)
        trade_log.append({
            'entry_dt': entry_dt, 'exit_dt': sigs[-1]['datetime'],
            'pnl_pct': cur_pnl, 'hold_h': hold_since_entry,
            'regime': entry_regime, 'exit_reason': 'OPEN_AT_END',
        })

    ret = (cash / 1000.0 - 1) * 100
    n = len(trade_log)
    wins = sum(1 for t in trade_log if t['pnl_pct'] > 0)
    wr = (wins / n * 100) if n else 0
    return ret, n, wr, blocked, max_hold_fires, max_hold_pnl_sum, trade_log


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--days', type=int, default=60, help='backtest window in days')
    ap.add_argument('--min-sell-pnl', type=float, default=0.5,
                    help='shield PnL threshold (single value, not swept)')
    ap.add_argument('--bull-holds', type=str, default='6,8,10,14,18')
    ap.add_argument('--bear-holds', type=str, default='6,8,10,14,18')
    ap.add_argument('--per-trade', action='store_true',
                    help='print per-trade detail of the WINNING combo')
    args = ap.parse_args()

    bull_holds = [int(x) for x in args.bull_holds.split(',')]
    bear_holds = [int(x) for x in args.bear_holds.split(',')]

    with open(REGIME_CFG) as f:
        cfg = json.load(f)
    asset_cfg = cfg['ETH']

    sigs = load_sigs()
    print(f"Cache: {len(sigs)} signals, "
          f"{sigs[0]['datetime']} -> {sigs[-1]['datetime']}")
    win = window_slice(sigs, args.days)
    print(f"{args.days}d window: {len(win)} signals\n")

    print(f"Live config (read-only):")
    print(f"  bull={asset_cfg['bull']['horizon']}h@{asset_cfg['bull']['min_confidence']}% "
          f"shield={'ON' if asset_cfg['bull'].get('hold_shield') else 'OFF'}")
    print(f"  bear={asset_cfg['bear']['horizon']}h@{asset_cfg['bear']['min_confidence']}% "
          f"shield={'ON' if asset_cfg['bear'].get('hold_shield') else 'OFF'}")
    print(f"  shared: min_sell_pnl={asset_cfg.get('min_sell_pnl_pct')}%, "
          f"max_hold={asset_cfg.get('max_hold_hours')}h\n")

    bull_rally = get_rally_tuple(asset_cfg, 'bull')
    bear_rally = get_rally_tuple(asset_cfg, 'bear')
    print(f"Gates: bull={bull_rally} | bear={bear_rally}\n")

    # Baseline #1: live config exactly as-is (read shared max_hold + per-regime shields from prod)
    cur_bull_shield = bool(asset_cfg.get('bull', {}).get('hold_shield', False))
    cur_bear_shield = bool(asset_cfg.get('bear', {}).get('hold_shield', False))
    cur_max_hold = int(asset_cfg.get('max_hold_hours', 10))
    cur_min_pnl = float(asset_cfg.get('min_sell_pnl_pct', 0.5))
    base_ret, base_n, base_wr, base_bl, base_mhf, base_mhp, _ = sim_regime_switched(
        win, asset_cfg, cur_min_pnl, cur_min_pnl,
        cur_max_hold, cur_max_hold, cur_bull_shield, cur_bear_shield,
        bull_rally, bear_rally)
    print(f"BASELINE (live config: {cur_max_hold}h/{cur_max_hold}h, "
          f"shields {cur_bull_shield}/{cur_bear_shield}, min_pnl {cur_min_pnl}%): "
          f"{base_ret:+.2f}% | {base_n} trades | WR {base_wr:.0f}% | "
          f"MAX_HOLD: {base_mhf} fires, sum {base_mhp:+.2f}%\n")

    print(f"Sweeping bull_hold in {bull_holds} x bear_hold in {bear_holds} x "
          f"4 shield combos = {len(bull_holds) * len(bear_holds) * 4} combos...\n")

    rows = []
    for bh, rh, bull_on, bear_on in product(
            bull_holds, bear_holds, [False, True], [False, True]):
        bmpnl = args.min_sell_pnl if bull_on else 0
        rmpnl = args.min_sell_pnl if bear_on else 0
        ret, n, wr, bl, mhf, mhp, _ = sim_regime_switched(
            win, asset_cfg, bmpnl, rmpnl, bh, rh, bull_on, bear_on,
            bull_rally, bear_rally)
        rows.append({
            'bull_hold': bh, 'bear_hold': rh,
            'bull_shield': bull_on, 'bear_shield': bear_on,
            'min_sell_pnl': args.min_sell_pnl,
            'return_pct': round(ret, 2), 'n_trades': n, 'win_rate': round(wr, 1),
            'blocked': bl, 'max_hold_fires': mhf, 'max_hold_pnl_sum': round(mhp, 2),
            'delta_vs_base': round(ret - base_ret, 2),
        })

    df = pd.DataFrame(rows).sort_values('return_pct', ascending=False)
    print("TOP 15 by return:")
    print(df.head(15).to_string(index=False))

    print("\nBOTTOM 5 by return:")
    print(df.tail(5).to_string(index=False))

    # Save
    out_path = os.path.join(
        ENGINE, 'output',
        f'per_regime_max_hold_{datetime.now().strftime("%Y%m%d_%H%M%S")}.csv')
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    df.to_csv(out_path, index=False)
    print(f"\nFull sweep saved to: {out_path}")

    # Per-trade detail of winner if requested
    if args.per_trade:
        win_row = df.iloc[0]
        print(f"\n{'='*80}")
        print(f"  PER-TRADE DETAIL OF WINNER: bull_hold={int(win_row['bull_hold'])}h "
              f"bear_hold={int(win_row['bear_hold'])}h "
              f"bull_shield={win_row['bull_shield']} bear_shield={win_row['bear_shield']}")
        print(f"{'='*80}")
        bmpnl = args.min_sell_pnl if win_row['bull_shield'] else 0
        rmpnl = args.min_sell_pnl if win_row['bear_shield'] else 0
        _, _, _, _, _, _, trades = sim_regime_switched(
            win, asset_cfg, bmpnl, rmpnl,
            int(win_row['bull_hold']), int(win_row['bear_hold']),
            bool(win_row['bull_shield']), bool(win_row['bear_shield']),
            bull_rally, bear_rally)
        for i, t in enumerate(trades, 1):
            ed = t['entry_dt'].strftime('%m-%d %H:%M')
            xd = t['exit_dt'].strftime('%m-%d %H:%M')
            print(f"  {i:>3} {ed} -> {xd}  {t['hold_h']:>3}h  "
                  f"{t['regime'][:4]:>4}  {t['exit_reason']:>10}  "
                  f"{t['pnl_pct']:+.2f}%")


if __name__ == '__main__':
    main()
