"""test_calibration_mode_d.py — Smoke test for Idea #2 Step 2:
LGBM probability calibration injected into Mode D's signal generation pipeline.

What this does (mirrors the fracdiff smoke-test pattern):
  1. Monkey-patches `crypto_trading_system_ed.generate_signals` with a
     calibration-wrapped version that does nested calibration:
       - Split training window 80/20 chronologically
       - Train each combo model on 80%
       - Fit Platt scaling on held-out 20%
       - Refit on full 100%
       - Apply Platt mapping at inference
     Method (platt | isotonic) selectable via env var CALIBRATION_METHOD.
  2. Runs Mode D in parallel for ETH 5,6,7,8h with --replay 1440
     --no-persist --no-data-update.
  3. Tags grid CSVs with _CALIB suffix so they don't collide with prod or
     fracdiff outputs.
  4. Audits: did the winning conf thresholds shift? Are the calibrated
     models picking different (combo, window, gamma)?

WAIT FOR FRACDIFF SMOKE TEST TO FINISH BEFORE RUNNING THIS.
Both write to models/crypto_ed_grid_ETH_<h>h.csv before tagging — concurrent
runs would race-condition.

Output:
  - models/crypto_ed_grid_ETH_<h>h_CALIB.csv (per horizon)
  - logs/calib_smoke_<h>h_<ts>.log (per horizon)
  - logs/calib_smoke_summary_<ts>.txt (cross-horizon audit)

Usage on Desktop:
  python tools/test_calibration_mode_d.py
  set CALIBRATION_METHOD=isotonic && python tools/test_calibration_mode_d.py
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime

ENGINE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TS = datetime.now().strftime('%Y%m%d_%H%M%S')

ASSET = 'ETH'
HORIZONS = [5, 6, 7, 8]
REPLAY_HOURS = 1440
PATCHER_NAME = '_calibration_patcher'
CALIB_METHOD = os.environ.get('CALIBRATION_METHOD', 'platt')


PATCHER_CODE = r'''"""Auto-generated by test_calibration_mode_d.py — DO NOT EDIT BY HAND.

Monkey-patches crypto_trading_system_ed.generate_signals with a
calibration-wrapped version. Uses nested 80/20 calibration per Niculescu-Mizil
& Caruana (2005). Method selectable via env var CALIBRATION_METHOD.
"""
import os
import warnings
import numpy as np
import pandas as pd

CALIB_METHOD = os.environ.get('CALIBRATION_METHOD', 'platt')

import crypto_trading_system_ed as _eng
_orig_generate_signals = _eng.generate_signals


def _calibrate_combo_predict(model_names, ALL_MODELS, X_train, y_train, sw, X_test, method):
    """Train each model with nested calibration. Returns avg calibrated proba[1]."""
    from sklearn.linear_model import LogisticRegression
    from sklearn.isotonic import IsotonicRegression

    n = len(X_train)
    split = int(0.8 * n)
    if split < 20 or n - split < 10:
        # Not enough data for a held-out fold — fall back to raw
        probas = []
        for mn in model_names:
            try:
                m = ALL_MODELS[mn]()
                m.fit(X_train, y_train, sample_weight=sw)
                probas.append(m.predict_proba(X_test)[:, 1])
            except Exception:
                continue
        if not probas:
            return None
        return np.mean(np.stack(probas, axis=0), axis=0)

    X_pre = X_train.iloc[:split]
    y_pre = y_train[:split]
    sw_pre = sw[:split]
    X_cal = X_train.iloc[split:]
    y_cal = y_train[split:]

    cal_test = []
    for mn in model_names:
        try:
            # Pre-fit on first 80%
            m_pre = ALL_MODELS[mn]()
            m_pre.fit(X_pre, y_pre, sample_weight=sw_pre)
            cal_scores = m_pre.predict_proba(X_cal)[:, 1]

            # Fit calibrator on held-out 20%
            if method == 'platt':
                calibrator = LogisticRegression()
                calibrator.fit(cal_scores.reshape(-1, 1), y_cal)
                def mapper(s, c=calibrator):
                    return c.predict_proba(s.reshape(-1, 1))[:, 1]
            else:  # isotonic
                calibrator = IsotonicRegression(out_of_bounds='clip')
                calibrator.fit(cal_scores, y_cal)
                def mapper(s, c=calibrator):
                    return c.predict(s)

            # Refit on full 100%
            m_full = ALL_MODELS[mn]()
            m_full.fit(X_train, y_train, sample_weight=sw)
            raw = m_full.predict_proba(X_test)[:, 1]
            cal_test.append(mapper(raw))
        except Exception as e:
            print(f"  [calib_patcher warn] {mn} failed: {e}")
            continue

    if not cal_test:
        return None
    return np.mean(np.stack(cal_test, axis=0), axis=0)


def generate_signals_calibrated(asset_name, model_names, window_size,
                                  replay_hours=None, feature_override=None,
                                  horizon=8, gamma=1.0):
    """Calibrated drop-in for engine.generate_signals.
    Mirrors original logic but replaces the per-cycle proba averaging with
    nested-calibration averaging.
    """
    from sklearn.preprocessing import StandardScaler
    from crypto_trading_system_ed import (load_data, _build_features,
                                          get_decay_weights, ALL_MODELS,
                                          _get_set_label, REPLAY_HOURS)

    if replay_hours is None:
        replay_hours = REPLAY_HOURS

    warnings.filterwarnings('ignore')
    set_label = _get_set_label() if feature_override is None else f"custom ({len(feature_override)} features)"
    gamma_str = f", gamma={gamma}" if gamma < 1.0 else ""
    print(f"\n  [CALIBRATED-{CALIB_METHOD}] Generating {horizon}h-ahead signals "
          f"for {asset_name} (models={'+'.join(model_names)}, window={window_size}h, "
          f"replay={replay_hours}h, {set_label}{gamma_str})...")

    df_raw = load_data(asset_name)
    if df_raw is None:
        return []

    df_features, feature_cols = _build_features(df_raw, asset_name,
                                                feature_override=feature_override,
                                                horizon=horizon)
    n = len(df_features)
    start_idx = max(window_size + 50, n - replay_hours)

    signals = []
    for i in range(start_idx, n):
        row = df_features.iloc[i]
        dt_str = row['datetime'].strftime('%Y-%m-%d %H:%M')

        train_start = max(0, i - window_size)
        train_end = max(train_start, i - horizon)
        train = df_features.iloc[train_start:train_end]
        X_train = train[feature_cols]
        y_train = train['label'].values
        X_test = df_features.iloc[i:i+1][feature_cols]

        if len(np.unique(y_train)) < 2:
            continue
        if X_train.isnull().any().any() or X_test.isnull().any().any():
            continue

        scaler = StandardScaler()
        X_train_s = pd.DataFrame(scaler.fit_transform(X_train), columns=feature_cols, index=X_train.index)
        X_test_s = pd.DataFrame(scaler.transform(X_test), columns=feature_cols, index=X_test.index)

        sw = get_decay_weights(len(y_train), gamma)
        cal_proba = _calibrate_combo_predict(model_names, ALL_MODELS, X_train_s,
                                             y_train, sw, X_test_s, CALIB_METHOD)
        if cal_proba is None:
            continue

        # Convert calibrated proba -> vote (replicates engine's majority-vote
        # logic but per-bar instead of per-model since we've already averaged).
        mean_proba = float(cal_proba[0])
        if mean_proba > 0.5:
            signal = 'BUY'
            confidence = mean_proba * 100
        elif mean_proba < 0.5:
            signal = 'SELL'
            confidence = (1 - mean_proba) * 100
        else:
            signal = 'HOLD'
            confidence = 50.0

        # Match the engine's signal dict shape (close, regime-tagger fills regime later)
        signals.append({
            'datetime': row['datetime'],
            'close': float(row['close']),
            'signal': signal,
            'confidence': float(confidence),
            'horizon': horizon,
        })

    print(f"  [CALIBRATED] generated {len(signals)} signals")
    return signals


_eng.generate_signals = generate_signals_calibrated
_CALIBRATION_PATCHED = True
print(f"[calibration_patcher] Patched generate_signals with {CALIB_METHOD} calibration")
'''


def write_patcher():
    path = os.path.join(ENGINE, f'{PATCHER_NAME}.py')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(PATCHER_CODE)
    print(f"  wrote patcher: {path}")
    return path


def cleanup_patcher():
    path = os.path.join(ENGINE, f'{PATCHER_NAME}.py')
    if os.path.exists(path):
        os.remove(path)
    pyc = os.path.join(ENGINE, '__pycache__', f'{PATCHER_NAME}.cpython-314.pyc')
    if os.path.exists(pyc):
        try:
            os.remove(pyc)
        except OSError:
            pass


WORKER_LAUNCHER = r'''
import os, sys, runpy
ENGINE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ENGINE)

# 1) Import patcher first
import {patcher}  # noqa: F401

# 2) Build engine argv as if called from CLI
sys.argv = ['crypto_trading_system_ed.py', 'D', '{asset}', '{horizon}h',
            '--replay', '{replay}', '--no-persist', '--no-data-update']

# 3) Run engine main
runpy.run_path(os.path.join(ENGINE, 'crypto_trading_system_ed.py'), run_name='__main__')
'''


def run_one_horizon(horizon: int, python_exe: str, log_dir: str) -> dict:
    launcher_name = f'_calib_runner_{horizon}h.py'
    launcher_path = os.path.join(ENGINE, launcher_name)
    code = WORKER_LAUNCHER.format(
        patcher=PATCHER_NAME,
        asset=ASSET,
        horizon=horizon,
        replay=REPLAY_HOURS,
    )
    with open(launcher_path, 'w', encoding='utf-8') as f:
        f.write(code)

    log_path = os.path.join(log_dir, f'calib_smoke_{horizon}h_{TS}.log')
    t0 = time.time()
    print(f"  [{horizon}h] LAUNCHING -> log: {log_path}")
    env = os.environ.copy()
    env['CALIBRATION_METHOD'] = CALIB_METHOD
    with open(log_path, 'w', encoding='utf-8') as logf:
        proc = subprocess.run(
            [python_exe, launcher_path],
            cwd=ENGINE,
            stdout=logf, stderr=subprocess.STDOUT,
            text=True, env=env,
        )
    elapsed = (time.time() - t0) / 60.0

    try:
        os.remove(launcher_path)
    except OSError:
        pass

    grid_src = os.path.join(ENGINE, 'models', f'crypto_ed_grid_{ASSET}_{horizon}h.csv')
    grid_dst = os.path.join(ENGINE, 'models', f'crypto_ed_grid_{ASSET}_{horizon}h_CALIB.csv')
    if os.path.exists(grid_src):
        shutil.copy2(grid_src, grid_dst)
    else:
        grid_dst = None

    return {
        'horizon': horizon,
        'exit_code': proc.returncode,
        'elapsed_min': round(elapsed, 1),
        'log_path': log_path,
        'grid_csv': grid_dst,
    }


def audit_results(results: list) -> str:
    import pandas as pd
    lines = []
    lines.append('=' * 100)
    lines.append(f"  CALIBRATION SMOKE TEST RESULTS — ETH {HORIZONS}h, --replay {REPLAY_HOURS}, "
                 f"method={CALIB_METHOD}")
    lines.append('=' * 100)

    # Compare to prod baseline
    prod_csv = os.path.join(ENGINE, 'models', 'crypto_ed_production.csv')
    prod_baseline = {}
    try:
        df_prod = pd.read_csv(prod_csv)
        for h in HORIZONS:
            rows = df_prod[(df_prod['coin'] == ASSET) & (df_prod['horizon'] == h)]
            if len(rows) > 0:
                top = rows.sort_values('combined_score', ascending=False).iloc[0]
                prod_baseline[h] = {
                    'combo': top['models'], 'window': int(top['best_window']),
                    'gamma': float(top['gamma']),
                    'return_pct': float(top.get('return_pct', 0)),
                    'apf': float(top.get('apf', 0)),
                }
    except Exception as e:
        lines.append(f"  (could not load prod baseline: {e})")

    for r in results:
        h = r['horizon']
        lines.append(f"\n  --- {h}h ---")
        lines.append(f"  exit_code={r['exit_code']}  elapsed={r['elapsed_min']}min  log={r['log_path']}")
        if r['exit_code'] != 0 or not r['grid_csv'] or not os.path.exists(r['grid_csv']):
            lines.append(f"  ERROR or grid CSV missing")
            continue

        df = pd.read_csv(r['grid_csv'])
        valid = df[df['status'] == 'OK']
        lines.append(f"  Grid: {len(df)} rows, {len(valid)} OK, "
                     f"{(df['status']=='FAILED').sum()} FAILED, "
                     f"{(df['status']=='LOW_TR').sum()} LOW_TR")

        if len(valid) > 0:
            best = valid.iloc[0]
            lines.append(f"  CALIBRATED best: combo={best.get('combo')} "
                         f"w={best.get('window')} g={best.get('gamma')} "
                         f"apf={best.get('apf'):.3f} ret={best.get('return_pct'):+.2f}% "
                         f"tr={best.get('trades')}")

            if h in prod_baseline:
                p = prod_baseline[h]
                lines.append(f"  PROD       best: combo={p['combo']} w={p['window']} g={p['gamma']} "
                             f"apf={p['apf']:.3f} ret={p['return_pct']:+.2f}%")
                # Quick comparison
                same_combo = best.get('combo') == p['combo']
                same_window = int(best.get('window')) == p['window']
                lines.append(f"  -> same combo? {same_combo}  same window? {same_window}  "
                             f"return delta: {best.get('return_pct') - p['return_pct']:+.2f}pp  "
                             f"apf delta: {best.get('apf') - p['apf']:+.3f}")

            # Top 5 calibrated configs
            lines.append(f"  Top 5 calibrated grid candidates:")
            for j, row in valid.head(5).iterrows():
                lines.append(f"    {row.get('combo'):<10} w={row.get('window'):3d} "
                             f"g={row.get('gamma')} f={row.get('n_features'):2d} "
                             f"apf={row.get('apf'):.3f} ret={row.get('return_pct'):+.2f}% "
                             f"tr={row.get('trades')}")

    lines.append('\n' + '=' * 100)
    lines.append("  VERDICT GUIDE:")
    lines.append("  - Calibrated APF >= prod baseline AND ret_delta >= +5pp on >=2 horizons")
    lines.append("    -> CALIBRATION HELPS. Move to step 3 (full HRST with calibration).")
    lines.append("  - Calibrated APF in (-5pp, +5pp) of prod -> noise; don't ship calibration.")
    lines.append("  - Calibrated APF << prod -> calibration HURTS. Skip.")
    lines.append("  - Different (combo, window) winners than prod -> calibration shifted")
    lines.append("    the optimization surface, possibly meaningfully. Worth looking at.")
    lines.append('=' * 100)
    return '\n'.join(lines)


def main():
    print("=" * 80)
    print(f"  CALIBRATION SMOKE TEST — ETH {HORIZONS}h, replay={REPLAY_HOURS}h, "
          f"method={CALIB_METHOD}")
    print(f"  Engine root: {ENGINE}")
    print(f"  Timestamp:   {TS}")
    print("=" * 80)

    print("\n  WARNING: This script writes to models/crypto_ed_grid_ETH_<h>h.csv "
          "before tagging.")
    print("  If the fracdiff smoke test is still running, ABORT and wait for it to finish.")
    print("  (fracdiff writes to the same paths; concurrent runs would race-condition.)")
    print()

    candidates = [
        r'C:\algo_trading\venv\Scripts\python.exe',
        r'C:\Users\Alex\algo_trading\venv\Scripts\python.exe',
        sys.executable,
    ]
    python_exe = next((p for p in candidates if os.path.exists(p)), sys.executable)
    print(f"  Python: {python_exe}")

    write_patcher()
    log_dir = os.path.join(ENGINE, 'logs')
    os.makedirs(log_dir, exist_ok=True)

    max_workers = int(os.environ.get('CALIB_PARALLEL', '2'))
    print(f"  Concurrency: {max_workers} horizon(s) at a time")

    t_start = time.time()
    results = []
    try:
        with ProcessPoolExecutor(max_workers=max_workers) as ex:
            futs = {ex.submit(run_one_horizon, h, python_exe, log_dir): h for h in HORIZONS}
            for fut in as_completed(futs):
                r = fut.result()
                results.append(r)
                tag = 'OK' if r['exit_code'] == 0 else f"FAIL ({r['exit_code']})"
                print(f"  [{r['horizon']}h] DONE {tag} ({r['elapsed_min']}min) — "
                      f"grid={r['grid_csv'] or 'MISSING'}")
    finally:
        cleanup_patcher()

    elapsed = (time.time() - t_start) / 60
    print(f"\n  All horizons done in {elapsed:.1f} min wall-clock.")

    results.sort(key=lambda r: r['horizon'])
    summary = audit_results(results)
    print(summary)

    summary_path = os.path.join(log_dir, f'calib_smoke_summary_{TS}.txt')
    with open(summary_path, 'w', encoding='utf-8') as f:
        f.write(summary)
    print(f"\n  Summary saved: {summary_path}")


if __name__ == '__main__':
    main()
