"""test_cdar_rescore.py — Smoke test for Idea #6: CDaR-aware Mode V scoring.

Chekhlov, Uryasev, Zabarankin (2005, *Mathematical Finance*) "Drawdown Measure
in Portfolio Optimization".

What it does:
  1. Monkey-patches Mode D's grid_rows builder to ALSO record max_dd_pct per
     candidate (the eval function already computes it internally; we just
     surface it).
  2. Runs Mode D ETH 5,6,7,8h with --no-persist --no-data-update.
  3. Tags grid CSVs with _CDAR suffix.
  4. Post-process: for each horizon, rerank candidates under multiple scoring
     functions:
        - current:    score = return * (WR/100) if return > 0 else return
        - return_only: score = return_pct
        - cdar_lam_X: score = return_pct - X * max_dd_pct  (X in {0.5, 1.0, 2.0, 5.0})
     Print top-3 under each scoring + rank correlation across schemes.

Decision: if CDaR_lam={0.5, 1.0, 2.0} top-3 includes configs with materially
LOWER max_dd at SIMILAR returns vs current top-3, ship.

NO production change. --no-persist / --no-data-update.

WAIT FOR ANY CURRENT MODE D TO FINISH BEFORE RUNNING.

Usage on Desktop:
  python tools/test_cdar_rescore.py
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime

ENGINE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TS = datetime.now().strftime('%Y%m%d_%H%M%S')

ASSET = 'ETH'
HORIZONS = [5, 6, 7, 8]
REPLAY_HOURS = 1440
PATCHER_NAME = '_cdar_patcher'


PATCHER_CODE = r'''"""Auto-generated by test_cdar_rescore.py — DO NOT EDIT BY HAND.

Monkey-patches crypto_trading_system_ed._deku_eval_with_pruning to also
include max_dd_pct in the returned tuple. The grid loop already extracts
max_dd indirectly (result[9]) but doesn't write it to grid_rows. We patch
the wrapper that writes the row.
"""
import numpy as np
import pandas as pd

import crypto_trading_system_ed as _eng
_orig_run_mode_d = _eng.run_mode_d_optuna

# We'll extend the grid_rows dict by a wrapper around _deku_eval_with_pruning.
# Engine's _deku_eval already returns max_dd*100 at index 9. We tag the result
# with a side-channel that the grid loop can read via thread-local.
import threading
_max_dd_capture = threading.local()


_orig_eval = _eng._deku_eval_with_pruning


def _eval_with_dd_capture(*args, **kwargs):
    res = _orig_eval(*args, **kwargs)
    if res is not None:
        try:
            _max_dd_capture.last = float(res[9])  # max_dd * 100
        except Exception:
            _max_dd_capture.last = float('nan')
    else:
        _max_dd_capture.last = float('nan')
    return res


_eng._deku_eval_with_pruning = _eval_with_dd_capture


# Now monkey-patch run_mode_d_optuna to inject max_dd_pct into grid_rows.
# Strategy: replace the grid CSV writer (right before to_csv) by wrapping the
# whole function. Simpler: hook pandas.DataFrame to add a column right before
# the grid CSV write. Easiest: patch the source-level dict construction by
# reading the engine source... too invasive.
#
# Cleanest: post-process the grid CSV after engine writes it, reconstruct
# max_dd from a parallel inline simulation. Since we can't easily capture
# per-row max_dd from a single-process eval, we do a SECOND pass: read the
# grid CSV, refit each top-N config, simulate, capture max_dd. This adds
# ~1-2 min per horizon (only top-15 configs, single fit each).
#
# That's done in the audit step, not at Mode D time. So this patcher is a
# no-op on Mode D output and just makes sure the eval function works.
print("[cdar_patcher] Loaded (eval wrapper installed for max_dd side-channel; "
      "audit pass refits top-N to compute max_dd cleanly)")
_CDAR_PATCHED = True
'''


def write_patcher():
    path = os.path.join(ENGINE, f'{PATCHER_NAME}.py')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(PATCHER_CODE)
    print(f"  wrote patcher: {path}")
    return path


def cleanup_patcher():
    path = os.path.join(ENGINE, f'{PATCHER_NAME}.py')
    if os.path.exists(path):
        os.remove(path)
    pyc = os.path.join(ENGINE, '__pycache__', f'{PATCHER_NAME}.cpython-314.pyc')
    if os.path.exists(pyc):
        try:
            os.remove(pyc)
        except OSError:
            pass


WORKER_LAUNCHER = r'''
import os, sys, runpy
ENGINE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ENGINE)

import {patcher}  # noqa: F401

sys.argv = ['crypto_trading_system_ed.py', 'D', '{asset}', '{horizon}h',
            '--replay', '{replay}', '--no-persist', '--no-data-update']
runpy.run_path(os.path.join(ENGINE, 'crypto_trading_system_ed.py'), run_name='__main__')
'''


def run_one_horizon(horizon: int, python_exe: str, log_dir: str) -> dict:
    launcher_name = f'_cdar_runner_{horizon}h.py'
    launcher_path = os.path.join(ENGINE, launcher_name)
    code = WORKER_LAUNCHER.format(
        patcher=PATCHER_NAME, asset=ASSET, horizon=horizon, replay=REPLAY_HOURS,
    )
    with open(launcher_path, 'w', encoding='utf-8') as f:
        f.write(code)
    log_path = os.path.join(log_dir, f'cdar_smoke_{horizon}h_{TS}.log')
    t0 = time.time()
    print(f"  [{horizon}h] LAUNCHING -> log: {log_path}")
    with open(log_path, 'w', encoding='utf-8') as logf:
        proc = subprocess.run(
            [python_exe, launcher_path], cwd=ENGINE,
            stdout=logf, stderr=subprocess.STDOUT, text=True,
        )
    elapsed = (time.time() - t0) / 60.0
    try:
        os.remove(launcher_path)
    except OSError:
        pass

    grid_src = os.path.join(ENGINE, 'models', f'crypto_ed_grid_{ASSET}_{horizon}h.csv')
    grid_dst = os.path.join(ENGINE, 'models', f'crypto_ed_grid_{ASSET}_{horizon}h_CDAR.csv')
    if os.path.exists(grid_src):
        shutil.copy2(grid_src, grid_dst)
    else:
        grid_dst = None
    return {'horizon': horizon, 'exit_code': proc.returncode,
            'elapsed_min': round(elapsed, 1), 'log_path': log_path,
            'grid_csv': grid_dst}


def refit_and_compute_dd(asset: str, horizon: int, combo: list, window: int,
                          gamma: float, n_features: int, replay_hours: int = 1440):
    """Refit the model with given config, walk-forward simulate, return
    (return_pct, max_dd_pct, cdar_5pct, n_trades)."""
    import numpy as np
    from crypto_trading_system_ed import (load_data, _build_features,
                                          _test_lgbm_importance, ALL_MODELS,
                                          get_decay_weights, DIAG_STEP,
                                          BACKTEST_FEE_PER_LEG, TRADING_FEE,
                                          _feature_floor_indices)

    df_raw = load_data(asset)
    if df_raw is None:
        return None

    df_features, feature_cols = _build_features(df_raw, asset, feature_override=None,
                                                horizon=horizon)
    # Get LGBM importance ranking
    df_clean = df_features.dropna(subset=feature_cols + ['label']).reset_index(drop=True)
    importance_df = _test_lgbm_importance(df_clean, feature_cols, gamma=1.0)
    ranked = importance_df['feature'].tolist()

    df_op = df_clean.dropna(subset=ranked + ['label']).reset_index(drop=True)
    sel_idx = _feature_floor_indices(ranked, n_features)
    features_np_all = df_op[ranked].values.astype(np.float64)
    labels_np_all = df_op['label'].values.astype(np.int32)
    closes_np_all = df_op['close'].values.astype(np.float64)

    n_total = len(df_op)
    train_n = int(0.6 * n_total)
    eval_start = train_n
    feat_np = features_np_all[:, sel_idx]

    # Walk-forward sim, tracking per-bar portfolio value
    min_start = max(window + 50, eval_start)
    portfolio = 1.0
    in_pos = False
    entry_px = 0
    trades = 0
    pv_series = []  # per-step portfolio values
    peak = 1.0
    max_dd = 0.0
    dd_series = []

    for i in range(min_start, n_total, DIAG_STEP):
        train_start = max(0, i - window)
        train_end = max(train_start, i - horizon)
        X_train = feat_np[train_start:train_end]
        y_train = labels_np_all[train_start:train_end]
        X_test = feat_np[i:i+1]
        if len(np.unique(y_train)) < 2 or np.isnan(X_train).any() or np.isnan(X_test).any():
            continue
        mean = X_train.mean(axis=0)
        std = X_train.std(axis=0); std[std == 0] = 1.0
        X_tr = (X_train - mean) / std
        X_te = (X_test - mean) / std
        sw = get_decay_weights(len(y_train), gamma)

        votes = []
        for mn in combo:
            try:
                m = ALL_MODELS[mn]()
                m.fit(X_tr, y_train, sample_weight=sw)
                votes.append(m.predict(X_te)[0])
            except Exception:
                continue
        if not votes:
            continue
        pred = 1 if sum(votes) / len(votes) > 0.5 else 0

        price = closes_np_all[i]
        if pred == 1 and not in_pos:
            in_pos = True
            entry_px = price * (1 + TRADING_FEE)
        elif pred == 0 and in_pos:
            sell_px = price * (1 - BACKTEST_FEE_PER_LEG)
            portfolio *= (1 + (sell_px - entry_px) / entry_px)
            trades += 1
            in_pos = False

        cur = portfolio * (price / entry_px) if in_pos else portfolio
        if cur > peak:
            peak = cur
        dd = (peak - cur) / peak
        dd_series.append(dd)
        if dd > max_dd:
            max_dd = dd
        pv_series.append(cur)

    if in_pos and trades >= 0:
        last_px = closes_np_all[n_total - 1]
        sell_px = last_px * (1 - BACKTEST_FEE_PER_LEG)
        portfolio *= (1 + (sell_px - entry_px) / entry_px)
        trades += 1

    ret_pct = (portfolio - 1.0) * 100
    max_dd_pct = max_dd * 100
    if dd_series:
        dd_arr = np.array(dd_series)
        # CDaR at alpha=5%: mean of worst 5% drawdowns
        thresh = np.quantile(dd_arr, 0.95)
        worst = dd_arr[dd_arr >= thresh]
        cdar_5pct = float(worst.mean() * 100) if len(worst) > 0 else max_dd_pct
    else:
        cdar_5pct = max_dd_pct
    return {'return_pct': ret_pct, 'max_dd_pct': max_dd_pct,
            'cdar_5pct': cdar_5pct, 'trades': trades}


def audit_with_cdar(results: list) -> str:
    import pandas as pd
    lines = []
    lines.append('=' * 100)
    lines.append(f"  CDaR RESCORE SMOKE TEST — ETH {HORIZONS}h")
    lines.append('=' * 100)

    LAMBDAS = [0.5, 1.0, 2.0, 5.0]

    for r in results:
        h = r['horizon']
        lines.append(f"\n  --- {h}h ---")
        lines.append(f"  exit_code={r['exit_code']}  elapsed={r['elapsed_min']}min")
        if r['exit_code'] != 0 or not r['grid_csv'] or not os.path.exists(r['grid_csv']):
            lines.append(f"  ERROR or grid CSV missing")
            continue
        df = pd.read_csv(r['grid_csv'])
        valid = df[df['status'] == 'OK'].head(15).copy()
        if len(valid) == 0:
            lines.append(f"  No OK candidates; skipping")
            continue

        lines.append(f"  Refitting top-{len(valid)} grid candidates to compute drawdown series...")
        for j, row in valid.iterrows():
            try:
                m = refit_and_compute_dd(
                    ASSET, h, str(row['combo']).split('+'),
                    int(row['window']), float(row['gamma']),
                    int(row['n_features']), REPLAY_HOURS,
                )
                if m is None:
                    valid.loc[j, 'max_dd_pct'] = float('nan')
                    valid.loc[j, 'cdar_5pct'] = float('nan')
                    valid.loc[j, 'sim_return_pct'] = float('nan')
                    valid.loc[j, 'sim_trades'] = 0
                else:
                    valid.loc[j, 'max_dd_pct'] = m['max_dd_pct']
                    valid.loc[j, 'cdar_5pct']  = m['cdar_5pct']
                    valid.loc[j, 'sim_return_pct'] = m['return_pct']
                    valid.loc[j, 'sim_trades'] = m['trades']
            except Exception as e:
                lines.append(f"    refit failed for row {j}: {e}")
                continue

        # Score under multiple objectives
        for lam in LAMBDAS:
            valid[f'cdar_score_lam{lam}'] = valid['return_pct'] - lam * valid['max_dd_pct']

        # Top-3 under current scoring (apf)
        top_curr = valid.sort_values('apf', ascending=False).head(3)
        lines.append(f"  Top-3 by current APF scoring:")
        for _, rr in top_curr.iterrows():
            lines.append(f"    apf={rr['apf']:.3f} ret={rr.get('return_pct', float('nan')):+.2f}% "
                         f"max_dd={rr.get('max_dd_pct', float('nan')):.2f}% "
                         f"combo={rr['combo']} w={rr['window']} g={rr['gamma']} f={rr['n_features']}")

        # Top-3 under each CDaR lambda
        for lam in LAMBDAS:
            top_cdar = valid.sort_values(f'cdar_score_lam{lam}', ascending=False).head(3)
            lines.append(f"  Top-3 by CDaR_score (lambda={lam}):")
            for _, rr in top_cdar.iterrows():
                lines.append(f"    score={rr[f'cdar_score_lam{lam}']:+.2f} ret={rr.get('return_pct', float('nan')):+.2f}% "
                             f"max_dd={rr.get('max_dd_pct', float('nan')):.2f}% "
                             f"combo={rr['combo']} w={rr['window']} g={rr['gamma']} f={rr['n_features']}")

        # Save the audited frame
        out_path = os.path.join(ENGINE, 'output', f'cdar_audit_ETH_{h}h_{TS}.csv')
        valid.to_csv(out_path, index=False)
        lines.append(f"  Audit CSV: {out_path}")

    lines.append('\n' + '=' * 100)
    lines.append("  VERDICT GUIDE:")
    lines.append("  - CDaR top-3 INCLUDES configs not in current top-3 with comparable returns AND lower max_dd")
    lines.append("    -> CDaR scoring meaningfully reranks. Consider promoting (1-line scoring change in engine).")
    lines.append("  - CDaR top-3 is identical to current top-3 across all lambdas")
    lines.append("    -> return and max_dd are highly correlated; CDaR adds nothing. Shelve.")
    lines.append("  - CDaR top-3 picks configs with much lower returns")
    lines.append("    -> lambda is too aggressive; doesn't matter, current scoring is better.")
    lines.append('=' * 100)
    return '\n'.join(lines)


def main():
    print("=" * 80)
    print(f"  CDaR RESCORE SMOKE TEST — ETH {HORIZONS}h, replay={REPLAY_HOURS}h")
    print("=" * 80)

    candidates = [
        r'C:\algo_trading\venv\Scripts\python.exe',
        r'C:\Users\Alex\algo_trading\venv\Scripts\python.exe',
        sys.executable,
    ]
    python_exe = next((p for p in candidates if os.path.exists(p)), sys.executable)
    print(f"  Python: {python_exe}")

    write_patcher()
    log_dir = os.path.join(ENGINE, 'logs')
    out_dir = os.path.join(ENGINE, 'output')
    os.makedirs(log_dir, exist_ok=True)
    os.makedirs(out_dir, exist_ok=True)

    max_workers = int(os.environ.get('CDAR_PARALLEL', '2'))
    print(f"  Concurrency: {max_workers} horizon(s)")

    t_start = time.time()
    results = []
    try:
        with ProcessPoolExecutor(max_workers=max_workers) as ex:
            futs = {ex.submit(run_one_horizon, h, python_exe, log_dir): h for h in HORIZONS}
            for fut in as_completed(futs):
                r = fut.result()
                results.append(r)
                tag = 'OK' if r['exit_code'] == 0 else f"FAIL ({r['exit_code']})"
                print(f"  [{r['horizon']}h] DONE {tag} ({r['elapsed_min']}min)")
    finally:
        cleanup_patcher()

    elapsed = (time.time() - t_start) / 60
    print(f"\n  Mode D phase done in {elapsed:.1f} min. Now refitting top candidates for CDaR...")

    results.sort(key=lambda r: r['horizon'])
    summary = audit_with_cdar(results)
    print(summary)

    summary_path = os.path.join(log_dir, f'cdar_smoke_summary_{TS}.txt')
    with open(summary_path, 'w', encoding='utf-8') as f:
        f.write(summary)
    print(f"\n  Summary saved: {summary_path}")


if __name__ == '__main__':
    main()
