"""test_stability_filter_mode_d.py — Smoke test for Idea #5: Feature stability filter.

Carhart-style robustness applied to feature ranking: a "real" feature must be
stable in importance across rolling sub-periods. If a feature ranks #5 in
days 1-30 of training but #45 in days 30-60, LGBM is using a feature whose
informativeness is time-unstable.

What this does:
  1. Monkey-patches `_test_lgbm_importance` to ALSO compute LGBM importance on
     3 rolling sub-windows (50% overlap) and DROP features whose rank movement
     across sub-windows exceeds threshold (default 30 positions).
  2. Runs Mode D for ETH 5,6,7,8h with --replay 1440 --no-persist --no-data-update.
  3. Tags grid CSVs with _STABILITY suffix.
  4. Audits whether the filtered Mode D produces stable winners with fewer
     features in winning configs.

Sweep override: STABILITY_RANK_THRESHOLD env var (default 30).

Outputs:
  - models/crypto_ed_grid_ETH_<h>h_STABILITY.csv  (per horizon)
  - logs/stability_smoke_<h>h_<ts>.log
  - logs/stability_smoke_summary_<ts>.txt

Usage on Desktop:
  python tools/test_stability_filter_mode_d.py
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime

ENGINE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TS = datetime.now().strftime('%Y%m%d_%H%M%S')

ASSET = 'ETH'
HORIZONS = [5, 6, 7, 8]
REPLAY_HOURS = 1440
PATCHER_NAME = '_stability_patcher'
RANK_THRESHOLD = int(os.environ.get('STABILITY_RANK_THRESHOLD', '30'))


PATCHER_CODE = r'''"""Auto-generated by test_stability_filter_mode_d.py — DO NOT EDIT BY HAND.

Monkey-patches crypto_trading_system_ed._test_lgbm_importance to filter out
features whose rank movement across rolling sub-windows exceeds RANK_THRESHOLD.
"""
import os
import numpy as np
import pandas as pd
from datetime import datetime

import crypto_trading_system_ed as _eng
_orig_test_importance = _eng._test_lgbm_importance

RANK_THRESHOLD = int(os.environ.get('STABILITY_RANK_THRESHOLD', '30'))


def _stability_filter_importance(df_clean, all_cols, gamma=1.0, **kwargs):
    """Compute LGBM importance on 3 sub-windows + filter unstable features.

    Sub-window strategy on training data df_clean:
      - sub_A: rows 0..50%   (oldest 50%)
      - sub_B: rows 25..75%  (middle 50%, 50% overlap with A and C)
      - sub_C: rows 50..100% (newest 50%)
    Each sub-window must yield a full ranking (one LGBM fit per sub-window).
    Then for each feature, compute max_rank - min_rank across the three.
    Drop features with movement > RANK_THRESHOLD before returning to engine.

    Returns the standard importance_df shape but filtered.
    """
    n = len(df_clean)
    if n < 1000:
        # Too few rows for stable sub-window ranks; return original.
        print(f"[stability_patcher] only {n} rows — skipping stability filter")
        return _orig_test_importance(df_clean, all_cols, gamma=gamma, **kwargs)

    s_size = n // 2
    sub_A = df_clean.iloc[0 : s_size]
    sub_B = df_clean.iloc[n // 4 : n // 4 + s_size]
    sub_C = df_clean.iloc[n - s_size : n]

    print(f"[stability_patcher] computing rank on 3 sub-windows "
          f"(sizes A={len(sub_A)}, B={len(sub_B)}, C={len(sub_C)})...")

    rank_A = _orig_test_importance(sub_A, all_cols, gamma=gamma)['feature'].tolist()
    rank_B = _orig_test_importance(sub_B, all_cols, gamma=gamma)['feature'].tolist()
    rank_C = _orig_test_importance(sub_C, all_cols, gamma=gamma)['feature'].tolist()

    # For each feature, get its rank in each sub-window (1-indexed). Features
    # missing from a ranking get rank = len(ranking) + 1 (worst possible).
    movements = {}
    for f in all_cols:
        rA = rank_A.index(f) + 1 if f in rank_A else len(rank_A) + 1
        rB = rank_B.index(f) + 1 if f in rank_B else len(rank_B) + 1
        rC = rank_C.index(f) + 1 if f in rank_C else len(rank_C) + 1
        movements[f] = max(rA, rB, rC) - min(rA, rB, rC)

    stable = [f for f in all_cols if movements[f] <= RANK_THRESHOLD]
    unstable = [f for f in all_cols if movements[f] > RANK_THRESHOLD]
    print(f"[stability_patcher] threshold={RANK_THRESHOLD}: kept {len(stable)} stable, "
          f"dropped {len(unstable)} unstable "
          f"(out of {len(all_cols)} total) — kept {len(stable)/max(1,len(all_cols))*100:.0f}%")

    if unstable:
        # Show top-10 most unstable for transparency
        sorted_unstable = sorted(unstable, key=lambda f: movements[f], reverse=True)[:10]
        print(f"[stability_patcher] top-10 most unstable (movement, feature):")
        for f in sorted_unstable:
            print(f"    {movements[f]:>4d}  {f}")

    if not stable:
        print(f"[stability_patcher] WARNING: 0 stable features survived; falling back to full set")
        return _orig_test_importance(df_clean, all_cols, gamma=gamma, **kwargs)

    # Now compute final ranking on FULL data using only stable features
    return _orig_test_importance(df_clean, stable, gamma=gamma, **kwargs)


_eng._test_lgbm_importance = _stability_filter_importance
_STABILITY_PATCHED = True
print(f"[stability_patcher] Patched _test_lgbm_importance "
      f"(rank_threshold={RANK_THRESHOLD})")
'''


def write_patcher():
    path = os.path.join(ENGINE, f'{PATCHER_NAME}.py')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(PATCHER_CODE)
    print(f"  wrote patcher: {path}")
    return path


def cleanup_patcher():
    path = os.path.join(ENGINE, f'{PATCHER_NAME}.py')
    if os.path.exists(path):
        os.remove(path)
    pyc = os.path.join(ENGINE, '__pycache__', f'{PATCHER_NAME}.cpython-314.pyc')
    if os.path.exists(pyc):
        try:
            os.remove(pyc)
        except OSError:
            pass


WORKER_LAUNCHER = r'''
import os, sys, runpy
ENGINE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ENGINE)
import {patcher}  # noqa: F401
sys.argv = ['crypto_trading_system_ed.py', 'D', '{asset}', '{horizon}h',
            '--replay', '{replay}', '--no-persist', '--no-data-update']
runpy.run_path(os.path.join(ENGINE, 'crypto_trading_system_ed.py'), run_name='__main__')
'''


def run_one_horizon(horizon: int, python_exe: str, log_dir: str) -> dict:
    launcher_name = f'_stability_runner_{horizon}h.py'
    launcher_path = os.path.join(ENGINE, launcher_name)
    code = WORKER_LAUNCHER.format(
        patcher=PATCHER_NAME, asset=ASSET, horizon=horizon, replay=REPLAY_HOURS,
    )
    with open(launcher_path, 'w', encoding='utf-8') as f:
        f.write(code)
    log_path = os.path.join(log_dir, f'stability_smoke_{horizon}h_{TS}.log')
    t0 = time.time()
    print(f"  [{horizon}h] LAUNCHING -> log: {log_path}")
    env = os.environ.copy()
    env['STABILITY_RANK_THRESHOLD'] = str(RANK_THRESHOLD)
    with open(log_path, 'w', encoding='utf-8') as logf:
        proc = subprocess.run(
            [python_exe, launcher_path], cwd=ENGINE,
            stdout=logf, stderr=subprocess.STDOUT, text=True, env=env,
        )
    elapsed = (time.time() - t0) / 60.0
    try:
        os.remove(launcher_path)
    except OSError:
        pass
    grid_src = os.path.join(ENGINE, 'models', f'crypto_ed_grid_{ASSET}_{horizon}h.csv')
    grid_dst = os.path.join(ENGINE, 'models', f'crypto_ed_grid_{ASSET}_{horizon}h_STABILITY.csv')
    if os.path.exists(grid_src):
        shutil.copy2(grid_src, grid_dst)
    else:
        grid_dst = None
    return {'horizon': horizon, 'exit_code': proc.returncode,
            'elapsed_min': round(elapsed, 1), 'log_path': log_path,
            'grid_csv': grid_dst}


def audit_results(results: list) -> str:
    import pandas as pd
    lines = []
    lines.append('=' * 100)
    lines.append(f"  STABILITY FILTER SMOKE TEST RESULTS — ETH {HORIZONS}h, "
                 f"--replay {REPLAY_HOURS}, rank_threshold={RANK_THRESHOLD}")
    lines.append('=' * 100)

    # Compare to existing baseline grid CSVs (un-tagged) — most recent prod run
    for r in results:
        h = r['horizon']
        lines.append(f"\n  --- {h}h ---")
        lines.append(f"  exit_code={r['exit_code']}  elapsed={r['elapsed_min']}min  log={r['log_path']}")
        if r['exit_code'] != 0 or not r['grid_csv'] or not os.path.exists(r['grid_csv']):
            lines.append(f"  ERROR or grid CSV missing")
            continue

        df_stab = pd.read_csv(r['grid_csv'])
        valid = df_stab[df_stab['status'] == 'OK']
        lines.append(f"  STABILITY grid: {len(df_stab)} rows, {len(valid)} OK")

        if len(valid) > 0:
            top = valid.sort_values('apf', ascending=False).head(5)
            lines.append(f"  Top 5 STABILITY-filtered candidates:")
            for _, row in top.iterrows():
                lines.append(f"    apf={row['apf']:.3f} ret={row['return_pct']:+.2f}% "
                             f"tr={row['trades']} {row['combo']:<10} w={row['window']:3d} "
                             f"g={row['gamma']} f={row['n_features']}")

        # Try to extract stability filter stats from the log
        try:
            with open(r['log_path'], encoding='utf-8') as f:
                log_text = f.read()
            for line in log_text.split('\n'):
                if 'stability_patcher' in line and 'kept' in line and 'dropped' in line:
                    lines.append(f"  Filter stats: {line.strip()}")
                    break
        except Exception as e:
            lines.append(f"  (could not parse log: {e})")

    # Cross-horizon: how many STABILITY top-1 winners share (combo, window)?
    top1_per_h = {}
    for r in results:
        if r['exit_code'] == 0 and r['grid_csv'] and os.path.exists(r['grid_csv']):
            df = pd.read_csv(r['grid_csv'])
            valid = df[df['status'] == 'OK']
            if len(valid) > 0:
                top1 = valid.sort_values('apf', ascending=False).iloc[0]
                top1_per_h[r['horizon']] = (top1['combo'], int(top1['window']))

    lines.append("\n" + '=' * 100)
    lines.append("  VERDICT GUIDE:")
    lines.append("  - >=2 horizons get HIGHER apf with FEWER features in winning config")
    lines.append("    -> stability filter helps. Consider integration.")
    lines.append("  - Apf within +/- 5% of unfiltered baseline AND same winners")
    lines.append("    -> noise; LGBM is robust to noisy features. Shelve.")
    lines.append("  - Apf significantly LOWER than baseline")
    lines.append("    -> filter dropped legitimate features (regime-dependent importance is REAL).")
    lines.append("       Lower threshold or shelve.")
    lines.append("  - Watch the dropped-feature list in logs for surprise drops of canonical features")
    lines.append("    (price_to_sma100h, logret_120h, pysr_*, etc.)")
    lines.append('=' * 100)
    return '\n'.join(lines)


def main():
    print("=" * 80)
    print(f"  STABILITY FILTER SMOKE TEST — ETH {HORIZONS}h, replay={REPLAY_HOURS}h, "
          f"rank_threshold={RANK_THRESHOLD}")
    print("=" * 80)

    candidates = [
        r'C:\algo_trading\venv\Scripts\python.exe',
        r'C:\Users\Alex\algo_trading\venv\Scripts\python.exe',
        sys.executable,
    ]
    python_exe = next((p for p in candidates if os.path.exists(p)), sys.executable)
    print(f"  Python: {python_exe}")

    write_patcher()
    log_dir = os.path.join(ENGINE, 'logs')
    os.makedirs(log_dir, exist_ok=True)

    max_workers = int(os.environ.get('STABILITY_PARALLEL', '2'))
    print(f"  Concurrency: {max_workers} horizon(s)")

    t_start = time.time()
    results = []
    try:
        with ProcessPoolExecutor(max_workers=max_workers) as ex:
            futs = {ex.submit(run_one_horizon, h, python_exe, log_dir): h for h in HORIZONS}
            for fut in as_completed(futs):
                r = fut.result()
                results.append(r)
                tag = 'OK' if r['exit_code'] == 0 else f"FAIL ({r['exit_code']})"
                print(f"  [{r['horizon']}h] DONE {tag} ({r['elapsed_min']}min)")
    finally:
        cleanup_patcher()

    elapsed = (time.time() - t_start) / 60
    print(f"\n  All horizons done in {elapsed:.1f} min wall-clock.")

    results.sort(key=lambda r: r['horizon'])
    summary = audit_results(results)
    print(summary)

    summary_path = os.path.join(log_dir, f'stability_smoke_summary_{TS}.txt')
    with open(summary_path, 'w', encoding='utf-8') as f:
        f.write(summary)
    print(f"\n  Summary saved: {summary_path}")


if __name__ == '__main__':
    main()
