"""test_fracdiff_mode_d.py — Smoke test for Idea #1 (fractional differentiation features).

What this does:
  1. Monkey-patches `build_hourly_features` to add 5 fractional-diff features
     (different d values on log-price + log-volume) WITHOUT modifying the engine
     source file.
  2. Runs Mode D (grid search) on ETH 5,6,7,8h with --replay 1440 in PARALLEL
     across the 4 horizons via subprocess.ProcessPoolExecutor.
     - --no-persist: writes to crypto_ed_production_noprod.csv
     - --no-data-update: skip macro+OHLCV redownload (must run AFTER engine
       has already updated data once today, OR you don't care about the freshest hour)
  3. After all 4 finish, audits which horizons selected fracdiff features in
     their grid winners + LGBM importance ranking.

The monkey-patch is in-process per subprocess — uses sitecustomize.py-style
trick: each subprocess imports a tiny patcher module FIRST, which patches the
engine, then runs the engine.

Output:
  - models/crypto_ed_grid_ETH_<h>h_FRACDIFF.csv  (grid results, tagged)
  - logs/fracdiff_smoke_<h>h_<ts>.log            (per-horizon log)
  - logs/fracdiff_smoke_summary_<ts>.txt         (cross-horizon audit)

Usage on Desktop:
  python tools/test_fracdiff_mode_d.py
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime

ENGINE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TS = datetime.now().strftime('%Y%m%d_%H%M%S')

ASSET = 'ETH'
HORIZONS = [5, 6, 7, 8]
REPLAY_HOURS = 1440  # 2 months
PATCHER_NAME = '_fracdiff_patcher'   # module name imported by each subprocess


# =============================================================================
# 1) Write the patcher module that subprocesses will import.
#    This module monkey-patches build_hourly_features to add fracdiff features.
# =============================================================================

PATCHER_CODE = r'''"""Auto-generated by test_fracdiff_mode_d.py — DO NOT EDIT BY HAND.

Monkey-patches crypto_trading_system_ed.build_all_features to add
fractional-differentiation features. Must be imported BEFORE the engine is
called.

Frac-diff is applied as a fixed-width-window FFD per Lopez de Prado AFML Ch 5.4
— preserves stationarity while keeping long memory in the series.
"""
import numpy as np
import pandas as pd

def _fracdiff_weights(d, threshold=1e-4):
    """Hosking (1981) recursion. w[0]=1, w[k] = -w[k-1] * (d - k + 1) / k.
    Truncate when |w[k]| < threshold."""
    w = [1.0]
    k = 1
    while True:
        w_k = -w[-1] * (d - k + 1) / k
        if abs(w_k) < threshold:
            break
        w.append(w_k)
        k += 1
        if k > 1000:
            break
    return np.array(w)


def _apply_fracdiff(values: np.ndarray, d: float, threshold: float = 1e-4) -> np.ndarray:
    """Vectorized fixed-width FFD via np.convolve.
    Returns array of same length as input; first (width-1) values are NaN.
    """
    w = _fracdiff_weights(d, threshold)
    width = len(w)
    n = len(values)
    out = np.full(n, np.nan)
    if n < width:
        return out
    vals = np.asarray(values, dtype=float)
    # We want, at index i: sum(w[k] * vals[i - k]) for k in 0..width-1.
    # That's a convolution with w (no reversal needed if we use the right mode).
    # np.convolve(vals, w[::-1], mode='valid') gives correlation at each position.
    # Simpler: explicit loop is acceptable here since width is small (~30 for d=0.4).
    for i in range(width - 1, n):
        window = vals[i - width + 1 : i + 1]
        if np.isnan(window).any():
            continue
        # window[0] = oldest; w[width-1] is the smallest weight applied to oldest
        # We want w[0]*vals[i] + w[1]*vals[i-1] + ... + w[width-1]*vals[i-width+1]
        out[i] = float(np.dot(w, window[::-1]))
    return out


# Patch build_all_features so Mode D's all_cols includes fracdiff features
import crypto_trading_system_ed as _eng
_orig_build_all = _eng.build_all_features
_FRACDIFF_FEATURES = ['fd_logclose_d03', 'fd_logclose_d04', 'fd_logclose_d05',
                      'fd_logvol_d04',  'fd_logvol_d05']


def build_all_features_with_fracdiff(df_hourly, asset_name='BTC', horizon=8,
                                      verbose=True, keep_label_nan_tail=False):
    df, all_cols = _orig_build_all(df_hourly, asset_name=asset_name, horizon=horizon,
                                   verbose=verbose, keep_label_nan_tail=keep_label_nan_tail)
    # Compute fracdiff on the RAW hourly input (preserves all timestamps), then
    # merge into df by datetime so dropna alignment is preserved.
    raw = df_hourly[['datetime', 'close', 'volume']].copy()
    raw['datetime'] = pd.to_datetime(raw['datetime'])
    raw = raw.sort_values('datetime').reset_index(drop=True)

    log_close = np.log(raw['close'].astype(float).clip(lower=1e-12).values)
    log_vol   = np.log1p(raw['volume'].astype(float).clip(lower=0.0).values)

    raw['fd_logclose_d03'] = _apply_fracdiff(log_close, 0.3)
    raw['fd_logclose_d04'] = _apply_fracdiff(log_close, 0.4)
    raw['fd_logclose_d05'] = _apply_fracdiff(log_close, 0.5)
    raw['fd_logvol_d04']   = _apply_fracdiff(log_vol,   0.4)
    raw['fd_logvol_d05']   = _apply_fracdiff(log_vol,   0.5)

    fd_block = raw[['datetime'] + _FRACDIFF_FEATURES]
    df['datetime'] = pd.to_datetime(df['datetime'])
    # Drop any pre-existing fd_* columns so merge doesn't suffix them
    for c in _FRACDIFF_FEATURES:
        if c in df.columns:
            df = df.drop(columns=[c])
    df = df.merge(fd_block, on='datetime', how='left')

    # Extend all_cols so Mode D's feature pipeline considers them
    for c in _FRACDIFF_FEATURES:
        if c not in all_cols:
            all_cols.append(c)

    if verbose:
        n_valid_pct = {c: int(df[c].notna().sum() / len(df) * 100) for c in _FRACDIFF_FEATURES}
        print(f"    [fracdiff_patcher] added {len(_FRACDIFF_FEATURES)} features "
              f"(valid coverage %: {n_valid_pct})")
    return df, all_cols


_eng.build_all_features = build_all_features_with_fracdiff
_FRACDIFF_PATCHED = True
print("[fracdiff_patcher] Patched build_all_features (+5 fracdiff features: "
      + ', '.join(_FRACDIFF_FEATURES) + ")")
'''


def write_patcher():
    path = os.path.join(ENGINE, f'{PATCHER_NAME}.py')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(PATCHER_CODE)
    print(f"  wrote patcher: {path}")
    return path


def cleanup_patcher():
    path = os.path.join(ENGINE, f'{PATCHER_NAME}.py')
    if os.path.exists(path):
        os.remove(path)
    pyc = os.path.join(ENGINE, '__pycache__', f'{PATCHER_NAME}.cpython-314.pyc')
    if os.path.exists(pyc):
        try:
            os.remove(pyc)
        except OSError:
            pass


# =============================================================================
# 2) Subprocess runner — for one horizon, fires a fresh python that imports
#    the patcher then runs Mode D for that single horizon.
# =============================================================================

WORKER_LAUNCHER = r'''
import os, sys, runpy
ENGINE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ENGINE)

# 1) Import the patcher FIRST — patches engine before anything else uses it.
import {patcher}  # noqa: F401

# 2) Build engine argv as if user had run it from CLI.
sys.argv = ['crypto_trading_system_ed.py', 'D', '{asset}', '{horizon}h',
            '--replay', '{replay}', '--no-persist', '--no-data-update']

# 3) Run engine main as if it were the CLI.
runpy.run_path(os.path.join(ENGINE, 'crypto_trading_system_ed.py'), run_name='__main__')
'''


def run_one_horizon(horizon: int, python_exe: str, log_dir: str) -> dict:
    """Spawn a subprocess that runs Mode D for one horizon with fracdiff patch."""
    launcher_name = f'_fracdiff_runner_{horizon}h.py'
    launcher_path = os.path.join(ENGINE, launcher_name)
    code = WORKER_LAUNCHER.format(
        patcher=PATCHER_NAME,
        asset=ASSET,
        horizon=horizon,
        replay=REPLAY_HOURS,
    )
    with open(launcher_path, 'w', encoding='utf-8') as f:
        f.write(code)

    log_path = os.path.join(log_dir, f'fracdiff_smoke_{horizon}h_{TS}.log')
    t0 = time.time()
    print(f"  [{horizon}h] LAUNCHING -> log: {log_path}")
    with open(log_path, 'w', encoding='utf-8') as logf:
        proc = subprocess.run(
            [python_exe, launcher_path],
            cwd=ENGINE,
            stdout=logf, stderr=subprocess.STDOUT,
            text=True,
        )
    elapsed = (time.time() - t0) / 60.0
    # Cleanup launcher
    try:
        os.remove(launcher_path)
    except OSError:
        pass

    # Tag grid CSV with FRACDIFF suffix so it doesn't get overwritten
    grid_src = os.path.join(ENGINE, 'models', f'crypto_ed_grid_{ASSET}_{horizon}h.csv')
    grid_dst = os.path.join(ENGINE, 'models', f'crypto_ed_grid_{ASSET}_{horizon}h_FRACDIFF.csv')
    if os.path.exists(grid_src):
        shutil.copy2(grid_src, grid_dst)
    else:
        grid_dst = None

    return {
        'horizon': horizon,
        'exit_code': proc.returncode,
        'elapsed_min': round(elapsed, 1),
        'log_path': log_path,
        'grid_csv': grid_dst,
    }


# =============================================================================
# 3) Audit — read the grid CSVs and check (a) feature selection, (b) LGBM
#    importance ranking (parsed from log).
# =============================================================================

def audit_results(results: list) -> str:
    import pandas as pd
    lines = []
    lines.append('=' * 100)
    lines.append(f"  FRACDIFF SMOKE TEST RESULTS — ETH {HORIZONS}h, --replay {REPLAY_HOURS}, "
                 f"--no-persist --no-data-update")
    lines.append('=' * 100)

    for r in results:
        h = r['horizon']
        lines.append(f"\n  --- {h}h ---")
        lines.append(f"  exit_code={r['exit_code']}  elapsed={r['elapsed_min']}min  "
                     f"log={r['log_path']}")
        if r['exit_code'] != 0:
            lines.append(f"  ERROR — Mode D failed; check log")
            continue
        if not r['grid_csv'] or not os.path.exists(r['grid_csv']):
            lines.append(f"  WARNING: grid CSV missing")
            continue

        df = pd.read_csv(r['grid_csv'])
        valid = df[df['status'] == 'OK']
        lines.append(f"  Grid: {len(df)} rows, {len(valid)} OK, "
                     f"{(df['status']=='FAILED').sum()} FAILED, "
                     f"{(df['status']=='LOW_TR').sum()} LOW_TR")

        # Check feature selection in the top candidates
        if 'features' in df.columns and len(valid) > 0:
            top = valid.head(20)
            fracdiff_keys = ['fd_logclose_d03', 'fd_logclose_d04', 'fd_logclose_d05',
                             'fd_logvol_d04', 'fd_logvol_d05']
            counts = {k: 0 for k in fracdiff_keys}
            for _, row in top.iterrows():
                feat_str = str(row.get('features', ''))
                for k in fracdiff_keys:
                    if k in feat_str:
                        counts[k] += 1
            lines.append(f"  Top-20 OK candidates feature inclusion:")
            for k, n in counts.items():
                pct = n / max(1, len(top)) * 100
                lines.append(f"    {k:<20}  {n:>2}/{len(top)} ({pct:.0f}%)")

            # Best valid candidate's full feature list
            best = valid.iloc[0]
            lines.append(f"  Best candidate: combo={best.get('combo')} window={best.get('window')} "
                         f"gamma={best.get('gamma')} apf={best.get('apf'):.3f} "
                         f"ret={best.get('return_pct'):+.2f}% tr={best.get('trades')}")
            best_feats = str(best.get('features', '')).split(',')
            best_fd = [f for f in best_feats if any(k in f for k in fracdiff_keys)]
            if best_fd:
                lines.append(f"  Best candidate INCLUDES fracdiff: {best_fd}")
            else:
                lines.append(f"  Best candidate did NOT pick any fracdiff feature.")

        # Try to extract LGBM importance ranking from the log
        try:
            with open(r['log_path'], encoding='utf-8') as f:
                log_text = f.read()
            # Look for "FEATURE IMPORTANCE" section
            if 'FEATURE IMPORTANCE' in log_text:
                idx = log_text.find('FEATURE IMPORTANCE')
                imp_block = log_text[idx:idx+4000]
                fd_lines = [ln for ln in imp_block.split('\n')
                            if any(k in ln for k in ['fd_logclose', 'fd_logvol'])]
                if fd_lines:
                    lines.append(f"  LGBM importance lines for fracdiff features:")
                    for ln in fd_lines[:10]:
                        lines.append(f"    {ln.strip()}")
                else:
                    lines.append(f"  (No fracdiff feature in LGBM importance top output)")
        except Exception as e:
            lines.append(f"  (could not parse importance from log: {e})")

    lines.append('\n' + '=' * 100)
    lines.append("  VERDICT GUIDE:")
    lines.append("  - If >= 5/20 of top candidates include any fracdiff feature -> earning grade.")
    lines.append("  - If best candidate INCLUDES fracdiff -> strong signal.")
    lines.append("  - If LGBM importance shows fracdiff in top-30 -> selectable in production.")
    lines.append("  - If NONE of the above -> fracdiff features are noise; revert.")
    lines.append('=' * 100)
    return '\n'.join(lines)


# =============================================================================
# 4) Main
# =============================================================================

def main():
    print("=" * 80)
    print(f"  FRACDIFF SMOKE TEST — ETH {HORIZONS}h, replay={REPLAY_HOURS}h, parallel")
    print(f"  Engine root: {ENGINE}")
    print(f"  Timestamp:   {TS}")
    print("=" * 80)

    # Pick the venv python (Desktop)
    candidates = [
        r'C:\algo_trading\venv\Scripts\python.exe',
        r'C:\Users\Alex\algo_trading\venv\Scripts\python.exe',
        sys.executable,
    ]
    python_exe = next((p for p in candidates if os.path.exists(p)), sys.executable)
    print(f"  Python:      {python_exe}")

    # Write the patcher
    write_patcher()

    log_dir = os.path.join(ENGINE, 'logs')
    os.makedirs(log_dir, exist_ok=True)

    # NOTE about parallelism: each Mode D internally uses N_JOBS_PARALLEL workers
    # for the grid sweep. Running 4 Mode D's concurrently would oversubscribe CPU.
    # The default below uses max_workers=2 (so 2 horizons run concurrently, each
    # using internal grid parallelism). Override via FRACDIFF_PARALLEL env var.
    max_workers = int(os.environ.get('FRACDIFF_PARALLEL', '2'))
    print(f"  Concurrency: {max_workers} horizon(s) at a time")
    print(f"  Per-horizon Mode D uses internal grid parallelism (N_JOBS_PARALLEL workers)")
    print(f"  -> total CPU load: ~{max_workers}× grid-worker count")

    t_start = time.time()
    results = []
    try:
        with ProcessPoolExecutor(max_workers=max_workers) as ex:
            futs = {ex.submit(run_one_horizon, h, python_exe, log_dir): h for h in HORIZONS}
            for fut in as_completed(futs):
                r = fut.result()
                results.append(r)
                tag = 'OK' if r['exit_code'] == 0 else f"FAIL ({r['exit_code']})"
                print(f"  [{r['horizon']}h] DONE {tag} ({r['elapsed_min']}min) — "
                      f"grid={r['grid_csv'] or 'MISSING'}")
    finally:
        cleanup_patcher()

    elapsed = (time.time() - t_start) / 60
    print(f"\n  All horizons done in {elapsed:.1f} min wall-clock.")

    results.sort(key=lambda r: r['horizon'])
    summary = audit_results(results)
    print(summary)

    summary_path = os.path.join(log_dir, f'fracdiff_smoke_summary_{TS}.txt')
    with open(summary_path, 'w', encoding='utf-8') as f:
        f.write(summary)
    print(f"\n  Summary saved: {summary_path}")


if __name__ == '__main__':
    main()
