"""
validate_core_point_in_time.py — Definitive PIT validation using archeology snapshots
======================================================================================

Created 2026-05-27 morning for TODO 0526.

PURPOSE
-------
For each entry in signal_log.csv within the validation window:
  1. Find the closest archeology snapshot of each input file (within ±15 min of H)
  2. Stage those snapshots in _pit_workdir/ (mirroring data/ structure)
  3. Run compute_signal_core() with the LIVE production config
  4. Compare core's signal to what signal_log[H] recorded

VALIDATION WINDOW
-----------------
Only samples from G_narrow promote (2026-05-21 21:56 UTC) onward. Before that,
the live trader was running a different config; comparing CURRENT config to
historical signals would be apples-to-oranges.

PRODUCTION SETUP UNTOUCHED
--------------------------
Uses V2_DATA_SNAPSHOT env var (engine's built-in snapshot redirect mechanism).
Engine reads from _pit_workdir/ for files we stage, falls back to data/ for files
we don't have archeology of (those features don't affect LIVE 5h/8h predictions).

EXPECTED OUTCOME
----------------
If core math is correct + archeology accurately reflects what live trader saw:
  - match rate ≥ 95% (signals match exactly)
  - avg conf delta ≈ 0 with stdev < 1.0 (small numerical noise from
    sklearn StandardScaler vs numpy)

If <95%: investigate the DIFF rows for systematic patterns (specific hours,
specific feature drift, etc.).

USAGE
-----
  python tools/validate_core_point_in_time.py
  python tools/validate_core_point_in_time.py --samples 50
  python tools/validate_core_point_in_time.py --tolerance-min 30
"""

import argparse
import io
import json
import os
import re
import shutil
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

# UTF-8 stdout (gentle — use reconfigure not wrapper to avoid engine import hang)
try:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass

import warnings
warnings.filterwarnings("ignore", message="X does not have valid feature names")

REPO_ROOT = Path(__file__).resolve().parent.parent
os.chdir(REPO_ROOT)
sys.path.insert(0, str(REPO_ROOT))

# ============================================================================
# CRITICAL: configure V2_DATA_SNAPSHOT *before* importing the engine, so its
# pd.read_csv monkey-patch installs with our working dir as the redirect target.
# ============================================================================
# IMPORTANT: the engine's V2_DATA_SNAPSHOT redirect computes filepath relative
# to engine root (e.g. 'data/eth_hourly_data.csv'), then maps to
# <snapshot>/data/eth_hourly_data.csv. So our staging tree MUST be
# WORKING_SNAPSHOT_DIR/data/<file> (with the data/ prefix), not WORKING_SNAPSHOT_DIR/<file>.
WORKING_SNAPSHOT_DIR = REPO_ROOT / "_pit_workdir"
WORKING_DATA_DIR = WORKING_SNAPSHOT_DIR / "data"
WORKING_DATA_DIR.mkdir(parents=True, exist_ok=True)
(WORKING_DATA_DIR / "macro_data").mkdir(parents=True, exist_ok=True)

# Clear conflicting env vars (V2_DATA_SNAPSHOT, redirected output dirs)
for v in ("H_STRICT_MODELS_DIR", "H_STRICT_CONFIG_DIR",
          "H75_WIDE_MODELS_DIR", "H75_WIDE_CONFIG_DIR"):
    if os.environ.get(v):
        del os.environ[v]

os.environ["V2_DATA_SNAPSHOT"] = str(WORKING_SNAPSHOT_DIR.relative_to(REPO_ROOT)).replace("\\", "/")

import pandas as pd
import numpy as np


# ============================================================================
# Constants
# ============================================================================
# G_narrow LIVE promote — only validate signals from this moment onward,
# because earlier signals were generated by different configs.
# Add 2h buffer for trader to reload new config (reloads every 5 min, but be safe).
LIVE_PROMOTE_DT = datetime(2026, 5, 21, 23, 56, tzinfo=timezone.utc)

# Files we have archeology of — these will be staged from snapshots.
# Files present in archeology are PIT-staged; files missing are read from current
# data/ (which means they carry whatever drift exists). Adding a file here is
# safe — if there's no archeology for it, the validator falls back to current.
ARCHEOLOGY_FILES = [
    # Priority 1 — primary ETH inputs (in PRESET_IMPORTANT, downloaded first)
    ("eth_hourly_data.csv", ""),                       # at data/ root
    ("derivatives_eth.csv", "macro_data"),             # at data/macro_data/
    ("onchain_eth.csv", "macro_data"),
    # Priority 2 — macro / cross-asset / sentiment (in PRESET_ALL, the 14-file extension)
    # These are the residual drift sources behind the 33% PIT validation gap.
    ("macro_daily.csv", "macro_data"),                 # VIX, DXY, S&P500, NASDAQ, Gold, etc.
    ("cross_asset.csv", "macro_data"),                 # xa_* features (DAX, S&P, NASDAQ rel-str)
    ("fear_greed.csv", "macro_data"),                  # fg_* sentiment
    ("stablecoin_flows.csv", "macro_data"),            # USDT/USDC market cap
    ("btc_hourly_data.csv", ""),                       # for xa_btc_usd_* cross-asset features
]

# Production-CSV / regime-config snapshots — used for point-in-time CONFIG lookup
# (which combo/window/gamma/features the live trader was using at signal_dt).
# Not staged into _pit_workdir — read directly to pull config dicts.
PROD_CSV_NAME = "crypto_ed_production.csv"
REGIME_JSON_NAME = "regime_config_ed.json"

# Archeology download root + extra frozen snapshot dirs (already on disk via Drive sync)
ARCHEOLOGY_ROOT = REPO_ROOT / "data" / "_archeology"
FROZEN_SNAPSHOT_DIRS = [
    REPO_ROOT / "data" / "_reliability_hrst_snapshot_laptop_20260522_0139",
    REPO_ROOT / "data" / "_reliability_hrst_snapshot_desktop_20260515_154801",
    REPO_ROOT / "data" / "_reliability_hrst_snapshot_laptop_20260515_102358",
    REPO_ROOT / "data" / "_reliability_hrst_snapshot_desktop_20260515_101439",
    REPO_ROOT / "data" / "_reliability_snapshot_20260514_233347",
    REPO_ROOT / "data" / "_v2_snapshot_20260514_120058",
    REPO_ROOT / "data" / "_diagnostic_snapshots" / "snap_20260526_2303",
    REPO_ROOT / "data" / "_diagnostic_snapshots" / "snap_20260526_2300",
]


# ============================================================================
# Snapshot index builder
# ============================================================================
def parse_snap_ts(folder_name):
    """Parse a snapshot folder name into a timezone-aware datetime.

    Handles two formats:
      snap_2026-05-21_07-00-51         (from drive_archeology.py)
      _reliability_hrst_snapshot_laptop_20260522_0139  (frozen snapshots, no second granularity)
    """
    # Drive archeology pattern: snap_YYYY-MM-DD_HH-MM-SS
    m = re.match(r"snap_(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})", folder_name)
    if m:
        y, mo, d, h, mi, s = map(int, m.groups())
        return datetime(y, mo, d, h, mi, s, tzinfo=timezone.utc)
    # Frozen snapshot pattern: ..._YYYYMMDD_HHMM (no seconds)
    m = re.search(r"(\d{4})(\d{2})(\d{2})_(\d{2})(\d{2})$", folder_name)
    if m:
        y, mo, d, h, mi = map(int, m.groups())
        return datetime(y, mo, d, h, mi, 0, tzinfo=timezone.utc)
    return None


def build_snapshot_index():
    """Return {(filename, subdir): [(timestamp, full_path), ...]} sorted by timestamp."""
    index = {(f, sd): [] for f, sd in ARCHEOLOGY_FILES}

    # ---- Archeology root: data/_archeology/<filename>/snap_<ts>/<filename> ----
    for filename, subdir in ARCHEOLOGY_FILES:
        arch_file_root = ARCHEOLOGY_ROOT / filename
        if not arch_file_root.exists():
            continue
        for snap_folder in arch_file_root.iterdir():
            if not snap_folder.is_dir():
                continue
            ts = parse_snap_ts(snap_folder.name)
            if ts is None:
                continue
            csv_path = snap_folder / filename
            if csv_path.exists():
                index[(filename, subdir)].append((ts, csv_path))

    # ---- Frozen snapshot dirs (full data/ mirror at one moment) ----
    for frozen_dir in FROZEN_SNAPSHOT_DIRS:
        if not frozen_dir.exists():
            continue
        ts = parse_snap_ts(frozen_dir.name)
        if ts is None:
            continue
        for filename, subdir in ARCHEOLOGY_FILES:
            if subdir:
                candidate = frozen_dir / subdir / filename
            else:
                candidate = frozen_dir / filename
            if candidate.exists():
                index[(filename, subdir)].append((ts, candidate))

    # Sort each list by timestamp
    for key in index:
        index[key].sort(key=lambda x: x[0])

    return index


def find_closest_snapshot(index_entries, target_dt, max_delta_minutes=360):
    """Find the snapshot timestamp closest to target_dt, within tolerance.

    Preference order (AFTER beats BEFORE):
      1. Snapshot taken AFTER target_dt — truncation drops the > target_dt rows,
         so the staged file's last row ≈ target_dt. Inference at signal_dt is
         then perfectly aligned.
      2. Snapshot taken BEFORE target_dt — staged file's last row is whenever
         the snapshot's last data row is, which can be HOURS older than
         signal_dt. The model trains on stale data and predicts at the wrong
         timestamp.

    Within each tier, pick the snapshot closest in time.

    Returns (chosen_ts, chosen_path) or None if nothing within tolerance.
    """
    if not index_entries:
        return None
    tolerance = timedelta(minutes=max_delta_minutes)

    # Tier 1: AFTER target (truncation gives data up to exactly target_dt)
    after = [(ts, p) for ts, p in index_entries
             if ts >= target_dt and ts - target_dt <= tolerance]
    if after:
        return min(after, key=lambda x: x[0] - target_dt)

    # Tier 2: BEFORE target (staged data is stale by however long ago snapshot was)
    before = [(ts, p) for ts, p in index_entries
              if ts < target_dt and target_dt - ts <= tolerance]
    if before:
        return max(before, key=lambda x: x[0])  # most recent before
    return None


def build_config_snapshot_index(filename):
    """Index of archeology snapshots of a single config-style file (prod CSV
    or regime config JSON).

    Returns sorted list of (timestamp, path) tuples.
    """
    out = []
    arch_file_root = ARCHEOLOGY_ROOT / filename
    if arch_file_root.exists():
        for snap_folder in arch_file_root.iterdir():
            if not snap_folder.is_dir():
                continue
            ts = parse_snap_ts(snap_folder.name)
            if ts is None:
                continue
            f = snap_folder / filename
            if f.exists():
                out.append((ts, f))
    out.sort(key=lambda x: x[0])
    return out


def build_merged_archeology(index_entries, filename):
    """Stack all snapshots oldest-first; for each row keep value from the
    OLDEST snapshot that contained it.

    Reverses the data-drift damage caused by keep='last' in download_macro_data:
    every snapshot's older rows have been overwritten by repeated re-fetches,
    so newer snapshots carry MORE drift than older ones. The oldest snapshot
    that contains a given row has the value closest to "originally observed".

    The merge keeps the ORIGINAL string format of the time column so the
    engine's pd.read_csv reads it identically to the current data/ file
    (no tz-awareness drift between merged and original).

    Returns (DataFrame, {snap_iso: rows_contributed}) or None if the file
    lacks a usable time column.
    """
    if not index_entries:
        return None

    sample_path = index_entries[0][1]
    sample_df = pd.read_csv(sample_path, nrows=5)
    key_col = None
    for cand in ("datetime", "date", "timestamp"):
        if cand in sample_df.columns:
            key_col = cand
            break
    if key_col is None:
        return None

    merged = None
    seen_keys = set()  # parsed-datetime set for deduplication
    snap_origin_count = {}
    for ts, path in index_entries:  # already sorted oldest -> newest
        try:
            df = pd.read_csv(path)
        except Exception:
            continue
        if key_col not in df.columns:
            continue
        # Parse to compare keys, but keep ORIGINAL string column intact for output.
        parsed = pd.to_datetime(df[key_col], errors="coerce", utc=True)
        df = df[parsed.notna()].copy()
        parsed = parsed[parsed.notna()]
        new_mask = ~parsed.isin(seen_keys)
        new_rows = df[new_mask.values]
        if len(new_rows):
            if merged is None:
                merged = new_rows.copy()
            else:
                merged = pd.concat([merged, new_rows], ignore_index=True)
            seen_keys.update(parsed[new_mask.values].tolist())
            snap_origin_count[ts.isoformat()] = len(new_rows)

    if merged is None:
        return None
    # Sort by parsed datetime (without mutating the original string column).
    sort_keys = pd.to_datetime(merged[key_col], errors="coerce", utc=True)
    merged = merged.iloc[sort_keys.argsort().values].reset_index(drop=True)
    return merged, snap_origin_count


def pick_config_snapshot_at(index_entries, target_dt):
    """Pick the prod-CSV / regime-config snapshot LIVE at target_dt.

    Prefers the most recent snapshot taken AT OR BEFORE target_dt — that's the
    file the trader's hot-reload would have been reading. Falls back to the
    earliest available if no eligible (≤target) snapshot exists.

    Returns (chosen_ts, chosen_path) or None if index is empty.
    """
    if not index_entries:
        return None
    eligible_before = [(ts, p) for ts, p in index_entries if ts <= target_dt]
    if eligible_before:
        return max(eligible_before, key=lambda x: x[0])
    return index_entries[0]  # earliest if nothing strictly before


# ============================================================================
# Stage snapshots into working dir for the engine to read
# ============================================================================
def _truncate_and_write(source, dest, signal_dt):
    """Read CSV from source, drop rows with datetime/date > signal_dt, write to dest.

    The point-in-time guarantee: the engine must only ever see rows that
    existed AT OR BEFORE signal_dt. Without truncation, the snapshot's last
    row could be hours past signal_dt, and the engine would train + predict
    on that future row — turning a PIT validation into a peeking validation.

    Returns (n_rows_kept, last_kept_timestamp_iso or None).
    """
    df = pd.read_csv(source)
    if df.empty:
        df.to_csv(dest, index=False)
        return (0, None)

    # Pick the time column. Macro/derivatives use 'date'; price uses 'datetime'.
    time_col = None
    for cand in ("datetime", "date", "timestamp"):
        if cand in df.columns:
            time_col = cand
            break

    if time_col is None:
        # No time column — can't truncate. Copy as-is.
        df.to_csv(dest, index=False)
        return (len(df), None)

    parsed = pd.to_datetime(df[time_col], errors="coerce", utc=True)
    # Drop rows with unparseable timestamps to be safe.
    keep_mask = parsed.notna() & (parsed <= signal_dt)
    df_trunc = df.loc[keep_mask].copy()
    df_trunc.to_csv(dest, index=False)
    last_ts = parsed[keep_mask].max() if keep_mask.any() else None
    return (len(df_trunc), last_ts.isoformat() if last_ts is not None else None)


def stage_snapshots(snapshots, signal_dt, log=None):
    """Copy chosen snapshot files into the working dir, truncated to <= signal_dt.

    Also deletes any staged file from a PRIOR iteration that's NOT in this
    iteration's snapshots list — without this, a file staged for sample N
    (because archeology was within tolerance then) would leak into sample N+1
    (whose archeology might be out-of-tolerance, expected to fall back to
    current data/). The redirect monkey-patch only falls back when the staged
    file doesn't exist, so we must remove stale stages explicitly.

    snapshots: list of (filename, subdir, source_path) tuples.
    signal_dt: timezone-aware datetime; all rows with time > signal_dt are dropped.
    Returns {filename: (n_rows, last_ts_iso)} for diagnostics.
    """
    (WORKING_DATA_DIR / "macro_data").mkdir(parents=True, exist_ok=True)
    stats = {}

    # First: clean stale stages — any file in ARCHEOLOGY_FILES that isn't being
    # restaged this iteration must be removed, so the engine falls back to live.
    staged_dest_paths = set()
    for filename, subdir, _ in snapshots:
        dest = (WORKING_DATA_DIR / subdir / filename) if subdir else (WORKING_DATA_DIR / filename)
        staged_dest_paths.add(dest)
    for filename, subdir in ARCHEOLOGY_FILES:
        dest = (WORKING_DATA_DIR / subdir / filename) if subdir else (WORKING_DATA_DIR / filename)
        if dest not in staged_dest_paths and dest.exists():
            try:
                dest.unlink()
            except PermissionError:
                time.sleep(0.5)
                try:
                    dest.unlink()
                except PermissionError:
                    pass  # leak rather than crash; the result is just one stale sample

    for filename, subdir, source in snapshots:
        if subdir:
            dest = WORKING_DATA_DIR / subdir / filename
        else:
            dest = WORKING_DATA_DIR / filename
        dest.parent.mkdir(parents=True, exist_ok=True)
        # Try a few times — Drive sync occasionally holds a short-lived lock
        for attempt in range(3):
            try:
                if dest.exists():
                    dest.unlink()
                n_rows, last_ts = _truncate_and_write(source, dest, signal_dt)
                stats[filename] = (n_rows, last_ts)
                break
            except PermissionError:
                if attempt == 2:
                    raise
                time.sleep(0.5)
    return stats


# ============================================================================
# Regime detection (sma24 > sma100 on price data)
# ============================================================================
def detect_regime_simple(price_csv_path, as_of_dt):
    """Compute regime at as_of_dt using sma24>sma100 on hourly close.

    Reads the staged eth_hourly_data.csv (point-in-time data).
    Returns 'bull' or 'bear'.
    """
    df = pd.read_csv(price_csv_path)
    if "datetime" not in df.columns:
        return "bull"
    df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")
    if df["datetime"].dt.tz is None:
        # naive timestamps — treat as UTC
        df["datetime"] = df["datetime"].dt.tz_localize("UTC")
    target_naive = as_of_dt.astimezone(timezone.utc).replace(tzinfo=None)
    df["dt_naive"] = df["datetime"].dt.tz_convert("UTC").dt.tz_localize(None)
    df = df[df["dt_naive"] <= target_naive].sort_values("dt_naive")
    if len(df) < 100:
        return "bull"
    closes = df["close"].astype(float)
    sma24 = closes.rolling(24).mean().iloc[-1]
    sma100 = closes.rolling(100).mean().iloc[-1]
    return "bull" if sma24 > sma100 else "bear"


# ============================================================================
# Main validation loop
# ============================================================================
def run_one_sample(asset, config, csc, engine, lt):
    """Build features + call compute_signal_core on whatever data is staged.

    Returns {'signal', 'confidence', 'horizon', 'error', 'n_features', 'n_train'}.
    """
    try:
        model_names = config["models"].split("+")
        window = int(config["best_window"])
        fs = config.get("feature_set", "A")
        horizon = int(config.get("horizon", lt.HORIZON_SHORT))
        opt_features = str(config.get("optimal_features", "") or "")
        gamma = float(config.get("gamma", 1.0))

        if fs in ("D", "E2", "E3") and opt_features and opt_features.strip() and opt_features.strip() != "nan":
            feature_list = [f.strip() for f in opt_features.split(",") if f.strip() and f.strip() != "nan"]
        elif fs == "B":
            feature_list = list(lt.FEATURE_SET_B)
        else:
            feature_list = list(lt.FEATURE_SET_A)

        # Load df_raw from the engine's own loader (uses the V2_DATA_SNAPSHOT redirect)
        df_raw = lt.load_data(asset)
        if df_raw is None or len(df_raw) == 0:
            return {"error": "df_raw_empty", "horizon": horizon}

        df_full, all_cols = engine.build_all_features(
            df_raw, asset_name=asset, horizon=horizon,
            verbose=False, keep_label_nan_tail=True,
        )
        engine._compute_pysr_features(df_full, all_cols, asset, horizon, verbose=False)

        feature_cols = [f for f in feature_list if f in all_cols]
        if not feature_cols:
            return {"error": "no_features", "horizon": horizon}

        df_train = df_full.dropna(subset=["label"]).reset_index(drop=True)
        df = df_full.reset_index(drop=True).copy()
        df[feature_cols] = df[feature_cols].ffill().fillna(0.0)
        df_train[feature_cols] = df_train[feature_cols].ffill().fillna(0.0)

        n_train = len(df_train)
        if n_train < window + 100:
            return {"error": f"insufficient_training({n_train}<{window+100})", "horizon": horizon}

        train_start = max(0, n_train - window)
        X_train = df_train.iloc[train_start:][feature_cols].values
        y_train = df_train.iloc[train_start:]["label"].values
        i = len(df) - 1
        X_test = df.iloc[i:i+1][feature_cols].values

        factories = {name: lt.ALL_MODELS[name] for name in model_names if name in lt.ALL_MODELS}
        if not factories:
            return {"error": f"no_models:{model_names}", "horizon": horizon}

        result = csc.compute_signal_core(
            X_train=X_train, y_train=y_train, X_test=X_test,
            model_factories=factories, gamma=gamma,
            na_policy="ffill", return_probas=True, binary_signal=False,
        )

        if result is None or result.get("signal") is None:
            return {"error": f"core_skipped:{result.get('skipped_reason') if result else None}",
                    "horizon": horizon}

        return {
            "signal": result["signal"],
            "confidence": result["confidence"],
            "horizon": horizon,
            "n_features": len(feature_cols),
            "n_train": len(y_train),
            "error": None,
        }
    except Exception as e:
        import traceback
        return {"error": f"{type(e).__name__}: {str(e)[:200]}",
                "traceback": traceback.format_exc()}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=int, default=100,
                        help="Max number of signal_log samples to validate (default 100)")
    parser.add_argument("--tolerance-min", type=int, default=1440,
                        help="Max minutes between signal_log timestamp and snapshot timestamp (default 1440 = 24h). "
                             "Because we truncate snapshots to <= signal_dt before staging, picking a snapshot taken "
                             "AFTER signal_dt is equivalent to picking one taken slightly before — the closest in "
                             "absolute time is preferred. Wide tolerance is safe; the only risk is sparse snapshots "
                             "missing very recent rows.")
    parser.add_argument("--asset", default="ETH")
    parser.add_argument("--limit-window-start", default=None,
                        help="Override LIVE promote start date (ISO format). Default: 2026-05-21T21:56")
    args = parser.parse_args()

    print("=" * 70)
    print("  PIT Validation — Core vs Live using Archeology Snapshots")
    print("=" * 70)
    print(f"  Asset: {args.asset}")
    print(f"  Validation window: {args.limit_window_start or LIVE_PROMOTE_DT.isoformat()} -> now")
    print(f"  Tolerance: ±{args.tolerance_min} min between signal_log and snapshot")
    print(f"  Max samples: {args.samples}")
    print(f"  V2_DATA_SNAPSHOT: {os.environ['V2_DATA_SNAPSHOT']}")
    print("=" * 70)

    # Build snapshot index
    print("\n[1/5] Building snapshot index from archeology + frozen snapshot dirs...")
    index = build_snapshot_index()
    for (filename, subdir), entries in index.items():
        loc = f"{subdir}/{filename}" if subdir else filename
        if entries:
            print(f"  {loc}: {len(entries)} snapshots, "
                  f"range {entries[0][0].isoformat()} -> {entries[-1][0].isoformat()}")
        else:
            print(f"  {loc}: NO snapshots — will fall back to current data/ file (may have drift)")

    # Build merged archeology (oldest-wins reconstruction) — once at startup.
    # For each file, stack all snapshots oldest-first and keep each row's value
    # from the OLDEST snapshot that contained it. This recovers values closest
    # to "originally observed" by undoing the data-drift damage from keep='last'.
    print("\n[1b/5] Building merged archeology (oldest-wins stacking)...")
    MERGED_CACHE = {}
    for (filename, subdir), entries in index.items():
        if not entries:
            continue
        result = build_merged_archeology(entries, filename)
        if result is None:
            print(f"  {filename}: no time column — skipped (will use individual snapshots)")
            continue
        merged_df, origins = result
        print(f"  {filename}: merged {len(merged_df)} rows from {len(origins)} snapshots")
        # Show top 3 contributors so we can see the oldest-snapshot dominates
        top = sorted(origins.items(), key=lambda x: -x[1])[:3]
        for ts_iso, n in top:
            print(f"      {ts_iso}: {n} rows")
        MERGED_CACHE[(filename, subdir)] = merged_df

    # Import engine (V2_DATA_SNAPSHOT already set above)
    print("\n[2/5] Importing engine + core (V2_DATA_SNAPSHOT redirect active)...")
    import crypto_signal_core as csc
    import crypto_trading_system_ed as engine
    import crypto_live_trader_ed as lt
    print("  Imports OK")

    # Build PIT prod-CSV index — each sample will pull the prod-CSV snapshot
    # that was LIVE at its signal_dt (the file the trader's hot-reload would
    # have been reading). Falls back to current models/crypto_ed_production.csv
    # if no archeology snapshot is available.
    print("\n[3/5] Building PIT prod-CSV index...")
    prod_index = build_config_snapshot_index(PROD_CSV_NAME)
    current_prod_path = REPO_ROOT / "models" / PROD_CSV_NAME
    # CRITICAL: include the CURRENT prod CSV with its mtime in the index. This
    # captures recent promotions (e.g., G_narrow on 2026-05-26) that aren't in
    # archeology because the user is on the same machine — Drive only versions
    # files when they're synced to another device. Without this, samples from
    # AFTER the most recent archeology snapshot would PIT-look-up an older
    # config than the trader was actually reading.
    if current_prod_path.exists():
        current_mtime_utc = datetime.fromtimestamp(
            current_prod_path.stat().st_mtime, tz=timezone.utc
        )
        prod_index.append((current_mtime_utc, current_prod_path))
        prod_index.sort(key=lambda x: x[0])
    if prod_index:
        print(f"  prod-CSV index: {len(prod_index)} entries, "
              f"range {prod_index[0][0].isoformat()} -> {prod_index[-1][0].isoformat()}")
        print(f"  (current models/{PROD_CSV_NAME} mtime: "
              f"{current_mtime_utc.isoformat() if current_prod_path.exists() else 'N/A'})")
    else:
        print(f"  prod-CSV: nothing — fatal")
        return

    # Load + filter signal_log
    print("\n[4/5] Loading + filtering signal_log...")
    sig_log = pd.read_csv("config/signal_log.csv")
    sig_log["timestamp"] = pd.to_datetime(sig_log["timestamp"], errors="coerce", utc=True)
    sig_log = sig_log[sig_log["asset"] == args.asset].dropna(subset=["timestamp"]).copy()
    sig_log = sig_log.sort_values("timestamp").reset_index(drop=True)

    window_start = LIVE_PROMOTE_DT
    if args.limit_window_start:
        window_start = datetime.fromisoformat(args.limit_window_start).replace(tzinfo=timezone.utc)

    in_window = sig_log[sig_log["timestamp"] >= window_start].reset_index(drop=True)
    print(f"  Total {args.asset} signals in log: {len(sig_log)}")
    print(f"  In window [{window_start.isoformat()} -> now]: {len(in_window)}")

    if len(in_window) == 0:
        print(f"  ERROR: no samples in window")
        return

    # Sample (cap at args.samples)
    if len(in_window) > args.samples:
        # Evenly-spaced sampling across the window
        idx = np.linspace(0, len(in_window) - 1, args.samples).astype(int)
        sampled = in_window.iloc[idx].reset_index(drop=True)
    else:
        sampled = in_window.reset_index(drop=True)
    print(f"  Sampling {len(sampled)} entries for validation")

    # Per-sample run
    print(f"\n[5/5] Running {len(sampled)} samples...")
    results = []
    n_match = n_diff = n_skip = 0

    # Position-based columns: sig_1 = lower horizon (bull), sig_2 = higher (bear).
    # The h_1/h_2 columns record the actual integer horizon for each slot, so we
    # don't have to guess from naming. Per-horizon-NaN means the trader didn't
    # run that model this cycle (regime-restricted mode).
    log_cols = sampled.columns.tolist()
    has_new_schema = "sig_1" in log_cols and "sig_2" in log_cols
    if has_new_schema:
        print(f"  signal_log: new schema (sig_1/sig_2, h_1/h_2)")
    else:
        # Fallback: very old logs might still have sig_4h/sig_8h
        print(f"  signal_log: legacy schema (sig_4h/sig_8h) — please migrate")
        raise SystemExit("Run the signal_log migration in tools/ to upgrade.")

    for i, row in sampled.iterrows():
        signal_dt = row["timestamp"]
        live_action_final = row["action"]                  # regime-resolved (BUY/SELL/HOLD post-threshold)
        live_conf_final = float(row["confidence"]) if pd.notna(row["confidence"]) else None
        live_price = float(row["price"]) if pd.notna(row["price"]) else None
        # Slot 1 → bull-regime model (lower horizon); slot 2 → bear (higher).
        # h_1/h_2 hold the integer horizon recorded by the trader at write time.
        live_sig_5h = row.get("sig_1") if "sig_1" in row.index else None
        live_conf_5h = float(row["conf_1"]) if "conf_1" in row.index and pd.notna(row.get("conf_1")) else None
        live_sig_8h = row.get("sig_2") if "sig_2" in row.index else None
        live_conf_8h = float(row["conf_2"]) if "conf_2" in row.index and pd.notna(row.get("conf_2")) else None
        live_h_1 = row.get("h_1") if "h_1" in row.index else None  # actual int horizon (5 or whatever bull was)
        live_h_2 = row.get("h_2") if "h_2" in row.index else None  # actual int horizon (8 or whatever bear was)

        # Stage from MERGED archeology (oldest-wins reconstruction) when available.
        # The merged file has each row's value from the OLDEST snapshot containing it,
        # which approximates pre-drift state. Truncation per sample (<=signal_dt) keeps
        # the PIT guarantee. Files without merged archeology fall back to individual
        # snapshot selection.
        snapshots_to_stage = []
        missing = []
        snapshot_ages_min = {}
        for filename, subdir in ARCHEOLOGY_FILES:
            if (filename, subdir) in MERGED_CACHE:
                # Write the merged DataFrame to a tmp path so stage_snapshots can
                # treat it like any other source file (apply truncation).
                merged_tmp = WORKING_SNAPSHOT_DIR / f"_merged_src_{filename}"
                if not merged_tmp.exists():
                    MERGED_CACHE[(filename, subdir)].to_csv(merged_tmp, index=False)
                snapshots_to_stage.append((filename, subdir, merged_tmp))
                snapshot_ages_min[filename] = 0  # merged = "as fresh as possible"
                continue
            # Fallback: pick closest individual snapshot
            chosen = find_closest_snapshot(
                index[(filename, subdir)], signal_dt,
                max_delta_minutes=args.tolerance_min,
            )
            if chosen is None:
                missing.append(filename)
            else:
                ts, path = chosen
                snapshots_to_stage.append((filename, subdir, path))
                delta_min = abs((ts - signal_dt).total_seconds()) / 60.0
                snapshot_ages_min[filename] = round(delta_min, 1)

        # Stage snapshots in working dir, truncated to <= signal_dt (PIT guarantee)
        staging_stats = stage_snapshots(snapshots_to_stage, signal_dt)

        # Determine regime + actual horizon from which sig_Xh slot is populated.
        # The h_1/h_2 columns hold the actual integer horizon the trader recorded.
        has_5h = live_sig_5h is not None and not (isinstance(live_sig_5h, float) and pd.isna(live_sig_5h)) and str(live_sig_5h).strip() != ""
        has_8h = live_sig_8h is not None and not (isinstance(live_sig_8h, float) and pd.isna(live_sig_8h)) and str(live_sig_8h).strip() != ""

        if has_5h and not has_8h:
            regime = "bull"
            actual_h = int(live_h_1) if live_h_1 is not None and not (isinstance(live_h_1, float) and pd.isna(live_h_1)) else 5
            live_sig_h, live_conf_h = live_sig_5h, live_conf_5h
        elif has_8h and not has_5h:
            regime = "bear"
            actual_h = int(live_h_2) if live_h_2 is not None and not (isinstance(live_h_2, float) and pd.isna(live_h_2)) else 8
            live_sig_h, live_conf_h = live_sig_8h, live_conf_8h
        elif has_5h and has_8h:
            # Both populated — old non-regime-restricted era. Fall back to local detector.
            price_path = WORKING_DATA_DIR / "eth_hourly_data.csv"
            regime = detect_regime_simple(price_path, signal_dt)
            if regime == "bull":
                actual_h = int(live_h_1) if live_h_1 is not None and not (isinstance(live_h_1, float) and pd.isna(live_h_1)) else 5
                live_sig_h, live_conf_h = live_sig_5h, live_conf_5h
            else:
                actual_h = int(live_h_2) if live_h_2 is not None and not (isinstance(live_h_2, float) and pd.isna(live_h_2)) else 8
                live_sig_h, live_conf_h = live_sig_8h, live_conf_8h
        else:
            print(f"  [{i+1}/{len(sampled)}] {signal_dt.isoformat()}  SKIP (sig_1 & sig_2 both empty — pre-rename bull-regime row)")
            n_skip += 1
            results.append({
                "timestamp": signal_dt.isoformat(),
                "live_action_final": live_action_final, "live_conf_final": live_conf_final,
                "live_sig_horizon": None, "live_conf_horizon": None,
                "live_price": live_price,
                "core_action": None, "core_conf": None,
                "match": None, "conf_delta": None,
                "regime": None, "horizon": None,
                "error": "no_sig_in_log",
                **{f"snap_age_min_{k}": v for k, v in snapshot_ages_min.items()},
            })
            continue

        # PIT config lookup — load the prod-CSV snapshot that was LIVE at signal_dt
        # (the file the trader's hot-reload would have been reading then).
        prod_chosen = pick_config_snapshot_at(prod_index, signal_dt)
        if prod_chosen:
            prod_ts, prod_path = prod_chosen
            prod_age_h = round((signal_dt - prod_ts).total_seconds() / 3600.0, 2)
        else:
            prod_path = current_prod_path
            prod_age_h = None
        prod_pit = pd.read_csv(prod_path)
        cfg_match = prod_pit[(prod_pit["coin"] == args.asset) & (prod_pit["horizon"] == actual_h)]
        if cfg_match.empty:
            print(f"  [{i+1}/{len(sampled)}] {signal_dt.isoformat()} {regime[:4]} h={actual_h}  "
                  f"SKIP (no PIT config for h={actual_h} in {prod_path.name})")
            n_skip += 1
            results.append({
                "timestamp": signal_dt.isoformat(),
                "live_action_final": live_action_final, "live_conf_final": live_conf_final,
                "live_sig_horizon": live_sig_h, "live_conf_horizon": live_conf_h,
                "live_price": live_price,
                "core_action": None, "core_conf": None,
                "match": None, "conf_delta": None,
                "regime": regime, "horizon": actual_h,
                "error": f"no_pit_config_h={actual_h}",
                "prod_age_h": prod_age_h,
                **{f"snap_age_min_{k}": v for k, v in snapshot_ages_min.items()},
            })
            continue
        config = cfg_match.iloc[0].to_dict()
        h = int(config["horizon"])

        # Run inference
        t0 = time.time()
        core = run_one_sample(args.asset, config, csc, engine, lt)
        elapsed = time.time() - t0

        if core.get("error"):
            print(f"  [{i+1}/{len(sampled)}] {signal_dt.isoformat()} {regime} h={config['horizon']}  "
                  f"ERROR: {core['error'][:60]}")
            n_skip += 1
            results.append({
                "timestamp": signal_dt.isoformat(),
                "live_action_final": live_action_final, "live_conf_final": live_conf_final,
                "live_sig_horizon": live_sig_h, "live_conf_horizon": live_conf_h,
                "live_price": live_price,
                "core_action": None, "core_conf": None,
                "match": None, "conf_delta": None,
                "regime": regime, "horizon": config["horizon"],
                "error": core["error"], "elapsed_s": round(elapsed, 2),
                "prod_age_h": prod_age_h,
                **{f"snap_age_min_{k}": v for k, v in snapshot_ages_min.items()},
            })
            continue

        # Compare core's raw signal against the live raw sig_Xh (NOT the
        # regime-resolved action which is post-threshold). If sig_Xh is missing
        # in the log (older format), skip the comparison.
        if live_sig_h is None or (isinstance(live_sig_h, float) and pd.isna(live_sig_h)) or str(live_sig_h).strip() == "":
            print(f"  [{i+1}/{len(sampled)}] {signal_dt.isoformat()} {regime[:4]} h={h}  "
                  f"SKIP (no sig_{h}h in signal_log row)")
            n_skip += 1
            results.append({
                "timestamp": signal_dt.isoformat(),
                "live_action_final": live_action_final, "live_conf_final": live_conf_final,
                "live_sig_horizon": live_sig_h, "live_conf_horizon": live_conf_h,
                "live_price": live_price,
                "core_action": core["signal"], "core_conf": core["confidence"],
                "match": None, "conf_delta": None,
                "regime": regime, "horizon": h,
                "error": f"no_sig_{h}h_in_log", "elapsed_s": round(elapsed, 2),
                **{f"snap_age_min_{k}": v for k, v in snapshot_ages_min.items()},
            })
            continue

        match = core["signal"] == str(live_sig_h)
        if match:
            n_match += 1
        else:
            n_diff += 1
        delta = (core["confidence"] - live_conf_h) if live_conf_h is not None else None

        marker = "MATCH" if match else "DIFF "
        stat_str = " ".join(f"{k.split('_')[0]}={v[0]}r" for k, v in staging_stats.items())
        prod_str = f"prod_age={prod_age_h}h" if prod_age_h is not None else "prod=current"
        print(f"  [{i+1}/{len(sampled)}] {signal_dt.isoformat()} {regime[:4]} h={h}  "
              f"live_sig_{h}h={live_sig_h}({live_conf_h}) core={core['signal']}({core['confidence']})  "
              f"{marker} ({elapsed:.1f}s) [{stat_str} {prod_str}]")

        results.append({
            "timestamp": signal_dt.isoformat(),
            "live_action_final": live_action_final, "live_conf_final": live_conf_final,
            "live_sig_horizon": live_sig_h, "live_conf_horizon": live_conf_h,
            "live_price": live_price,
            "core_action": core["signal"], "core_conf": core["confidence"],
            "match": match, "conf_delta": round(delta, 2) if delta is not None else None,
            "regime": regime, "horizon": h,
            "best_combo": config.get("best_combo"),
            "best_window": config.get("best_window"),
            "gamma": config.get("gamma"),
            "prod_age_h": prod_age_h,
            "n_features": core.get("n_features"),
            "n_train": core.get("n_train"),
            "error": None, "elapsed_s": round(elapsed, 2),
            **{f"snap_age_min_{k}": v for k, v in snapshot_ages_min.items()},
        })

    # Save results
    df_res = pd.DataFrame(results)
    ts_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = Path("output") / f"core_pit_validation_{ts_str}.csv"
    out_path.parent.mkdir(exist_ok=True)
    df_res.to_csv(out_path, index=False)

    # Cleanup working dir (optional; comment out if you want to inspect the last staged state)
    # for entry in WORKING_SNAPSHOT_DIR.iterdir():
    #     if entry.is_dir(): shutil.rmtree(entry)
    #     else: entry.unlink()

    # Summary
    n_valid = n_match + n_diff
    print("\n" + "=" * 70)
    print("  PIT VALIDATION RESULT")
    print("=" * 70)
    print(f"  Samples attempted: {len(sampled)}")
    print(f"  Successfully evaluated: {n_valid}")
    print(f"  Skipped (no snapshot / error): {n_skip}")
    print()
    print(f"  NOTE on SKIPs:")
    print(f"    Bull-regime rows logged BEFORE the 2026-05-27 trader rename have BOTH")
    print(f"    sig_1 and sig_2 empty because the old _log_signal looked up")
    print(f"    sigs_by_horizon.get(HORIZON_SHORT=4) — but the bull model runs at h=5,")
    print(f"    so that lookup always returned None. Post-restart, sig_1 fills from")
    print(f"    sorted-horizon position 0 and bull-regime samples become validatable.")
    print()
    print(f"  NOTE on DIFFs:")
    print(f"    Core uses staged truncated archeology data for ETH+derivatives+onchain;")
    print(f"    all other features (macro, cross-asset, sentiment, pysr) come from")
    print(f"    CURRENT data/ which may have drifted (data drift was patched 2026-05-26).")
    print(f"    Adjacent samples within ~24h often pull the SAME closest snapshot, so")
    print(f"    identical core outputs across consecutive timestamps are expected.")
    if n_valid:
        match_rate = 100 * n_match / n_valid
        print(f"  MATCH: {n_match}/{n_valid} = {match_rate:.1f}%")
        print(f"  DIFF:  {n_diff}/{n_valid} = {100 - match_rate:.1f}%")
        valid_df = df_res[df_res["error"].isna() & df_res["match"].notna()]
        if "conf_delta" in valid_df.columns and valid_df["conf_delta"].notna().any():
            print(f"  Avg conf delta:    {valid_df['conf_delta'].mean():+.3f}")
            print(f"  Stdev conf delta:  {valid_df['conf_delta'].std():.3f}")
            print(f"  Max abs delta:     {valid_df['conf_delta'].abs().max():.2f}")
        # Per-horizon
        print(f"\n  Per-horizon match rate:")
        for h in sorted(df_res["horizon"].dropna().unique()):
            sub = valid_df[valid_df["horizon"] == h]
            if len(sub):
                mr = 100 * sub["match"].sum() / len(sub)
                print(f"    horizon={int(h)}: {int(sub['match'].sum())}/{len(sub)} = {mr:.1f}%")
        # Match rate vs snapshot freshness — older snapshots = more data drift
        if "snap_age_min_eth_hourly_data.csv" in valid_df.columns:
            ages = valid_df["snap_age_min_eth_hourly_data.csv"].dropna()
            if len(ages):
                match_ages = valid_df.loc[valid_df["match"] == True, "snap_age_min_eth_hourly_data.csv"]
                diff_ages = valid_df.loc[valid_df["match"] == False, "snap_age_min_eth_hourly_data.csv"]
                print(f"\n  Snapshot freshness vs match (eth_hourly_data.csv):")
                if len(match_ages):
                    print(f"    MATCH avg age: {match_ages.mean():>6.1f} min  (n={len(match_ages)})")
                if len(diff_ages):
                    print(f"    DIFF  avg age: {diff_ages.mean():>6.1f} min  (n={len(diff_ages)})")
                if len(match_ages) and len(diff_ages):
                    if match_ages.mean() < diff_ages.mean():
                        print(f"    -> DIFFs use staler snapshots — gap is data drift, not core math")
        # Verdict
        print()
        if match_rate >= 95:
            print("  [OK] CORE VALIDATED — match rate ≥ 95%. Safe to proceed to Step 6 (engine refactor).")
        elif match_rate >= 80:
            print(f"  [PARTIAL] {match_rate:.1f}% — investigate DIFF rows before refactor.")
        else:
            print(f"  [FAIL] {match_rate:.1f}% — core or replication issue. Debug before refactor.")
    print(f"\n  Full results: {out_path}")
    print("=" * 70)


if __name__ == "__main__":
    main()
